/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AmapContainer: typeof import('./src/components/AmapContainer.vue')['default']
    AmapExample: typeof import('./src/components/AmapExample.vue')['default']
    CommentsRatings: typeof import('./src/components/CommentsRatings.vue')['default']
    EarthComponent: typeof import('./src/components/EarthComponent.vue')['default']
    EarthGlobe: typeof import('./src/components/EarthGlobe.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PersonaCharacter: typeof import('./src/components/personas/PersonaCharacter.vue')['default']
    PersonalityCharacter: typeof import('./src/components/PersonalityCharacter.vue')['default']
    PersonaShowcase: typeof import('./src/components/personas/PersonaShowcase.vue')['default']
    PersonaSVG: typeof import('./src/components/personas/PersonaSVG.vue')['default']
    PESC: typeof import('./src/components/personas/PESC.vue')['default']
    PEScKPI: typeof import('./src/components/personas/PESc-KPI.vue')['default']
    PEscTool: typeof import('./src/components/personas/PEsc-Tool.vue')['default']
    PEsCWifi: typeof import('./src/components/personas/PEsC-Wifi.vue')['default']
    PReC: typeof import('./src/components/personas/PReC.vue')['default']
    PRsC: typeof import('./src/components/personas/PRsC.vue')['default']
    PRscMoney: typeof import('./src/components/personas/PRsc-Money.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartDiaryEditor: typeof import('./src/components/SmartDiaryEditor.vue')['default']
    TripSelectorModal: typeof import('./src/components/TripSelectorModal.vue')['default']
    WESc: typeof import('./src/components/personas/WESc.vue')['default']
    WESCGPS: typeof import('./src/components/personas/WESC-GPS.vue')['default']
    WEsCSignal: typeof import('./src/components/personas/WEsC-Signal.vue')['default']
    WReC: typeof import('./src/components/personas/WReC.vue')['default']
    WRsC: typeof import('./src/components/personas/WRsC.vue')['default']
  }
}
