// 生成美食数据
const generateFoodsData = () => {
  const foods = []
  let id = 1

  // 北京美食 (30个)
  addCityFoods('北京', [
    { name: '北京烤鸭', cuisine_type: '京菜', rating: 4.7, price_range: '¥17-54', is_featured: true, tags: ['必吃', '特色'], description: '北京特色美食' },
    { name: '老北京炸酱面', cuisine_type: '京菜', rating: 4.8, price_range: '¥18-66', is_featured: true, tags: ['必吃', '特色'], description: '北京特色美食' },
    { name: '涮羊肉', cuisine_type: '京菜', rating: 4.4, price_range: '¥14-38', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '豆汁儿', cuisine_type: '京菜', rating: 4.3, price_range: '¥13-56', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '卤煮火烧', cuisine_type: '京菜', rating: 4.3, price_range: '¥13-56', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '爆肚', cuisine_type: '京菜', rating: 4.2, price_range: '¥22-64', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '门钉肉饼', cuisine_type: '京菜', rating: 4.4, price_range: '¥24-48', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '炙子烤肉', cuisine_type: '京菜', rating: 4.5, price_range: '¥25-50', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '炒肝', cuisine_type: '京菜', rating: 4.7, price_range: '¥27-74', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '豌豆黄', cuisine_type: '京菜', rating: 4.0, price_range: '¥10-40', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '炸灌肠', cuisine_type: '京菜', rating: 4.0, price_range: '¥20-40', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '麻酱糖饼', cuisine_type: '京菜', rating: 4.8, price_range: '¥18-56', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '焦圈', cuisine_type: '京菜', rating: 4.3, price_range: '¥23-46', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '艾窝窝', cuisine_type: '京菜', rating: 4.0, price_range: '¥10-50', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '玫瑰饼', cuisine_type: '京菜', rating: 4.6, price_range: '¥26-72', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '牛舌饼', cuisine_type: '京菜', rating: 4.5, price_range: '¥15-60', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '糖葫芦', cuisine_type: '京菜', rating: 4.0, price_range: '¥10-30', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '茯苓饼', cuisine_type: '京菜', rating: 4.7, price_range: '¥27-54', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '正明斋糕点', cuisine_type: '京菜', rating: 4.3, price_range: '¥13-36', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '京八件', cuisine_type: '京菜', rating: 4.4, price_range: '¥14-38', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '驴打滚', cuisine_type: '京菜', rating: 4.2, price_range: '¥12-44', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '奶油炸糕', cuisine_type: '京菜', rating: 4.3, price_range: '¥13-36', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '面茶', cuisine_type: '京菜', rating: 4.3, price_range: '¥13-46', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '小吊梨汤', cuisine_type: '京菜', rating: 4.2, price_range: '¥22-44', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '葱烧海参', cuisine_type: '京菜', rating: 4.4, price_range: '¥14-38', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '京酱肉丝', cuisine_type: '京菜', rating: 4.3, price_range: '¥23-46', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '九转大肠', cuisine_type: '京菜', rating: 4.5, price_range: '¥25-60', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '枣钱饼', cuisine_type: '京菜', rating: 4.3, price_range: '¥23-46', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '吹糖人', cuisine_type: '京菜', rating: 4.4, price_range: '¥24-68', is_featured: false, tags: ['特色'], description: '北京特色美食' },
    { name: '柳泉居面点', cuisine_type: '京菜', rating: 4.3, price_range: '¥23-46', is_featured: false, tags: ['特色'], description: '北京特色美食' },
  ])

  // 长沙美食 (28个)
  addCityFoods('长沙', [
    { name: '长沙臭豆腐', cuisine_type: '湘菜', rating: 4.8, price_range: '¥18-66', is_featured: true, tags: ['必吃', '特色'], description: '长沙特色美食' },
    { name: '糖油粑粑', cuisine_type: '湘菜', rating: 4.0, price_range: '¥10-40', is_featured: true, tags: ['必吃', '特色'], description: '长沙特色美食' },
    { name: '口味虾', cuisine_type: '湘菜', rating: 4.8, price_range: '¥18-46', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '湖南酱板鸭', cuisine_type: '湘菜', rating: 4.1, price_range: '¥11-52', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '长沙米粉', cuisine_type: '湘菜', rating: 4.9, price_range: '¥29-78', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '德园包子', cuisine_type: '湘菜', rating: 4.2, price_range: '¥12-54', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '龙脂猪血', cuisine_type: '湘菜', rating: 4.6, price_range: '¥26-72', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '嗍螺', cuisine_type: '湘菜', rating: 4.0, price_range: '¥10-30', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '红烧猪脚', cuisine_type: '湘菜', rating: 4.1, price_range: '¥11-32', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '口味蟹', cuisine_type: '湘菜', rating: 4.7, price_range: '¥17-44', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '辣椒炒肉', cuisine_type: '湘菜', rating: 4.8, price_range: '¥18-66', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '剁椒鱼头', cuisine_type: '湘菜', rating: 4.7, price_range: '¥27-74', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '蒸菜', cuisine_type: '湘菜', rating: 4.5, price_range: '¥25-50', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '刮凉粉', cuisine_type: '湘菜', rating: 4.5, price_range: '¥15-50', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '油炸串串', cuisine_type: '湘菜', rating: 4.5, price_range: '¥15-60', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '茶颜悦色', cuisine_type: '湘菜', rating: 4.1, price_range: '¥21-52', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '小龙虾', cuisine_type: '湘菜', rating: 4.8, price_range: '¥18-46', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '甜酒冲蛋', cuisine_type: '湘菜', rating: 4.2, price_range: '¥12-54', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '毛氏红烧肉', cuisine_type: '湘菜', rating: 4.7, price_range: '¥17-64', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '冰粉', cuisine_type: '湘菜', rating: 4.4, price_range: '¥14-58', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '姊妹团子', cuisine_type: '湘菜', rating: 4.7, price_range: '¥17-44', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '荷兰粉', cuisine_type: '湘菜', rating: 4.5, price_range: '¥15-40', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '麻辣子鸡', cuisine_type: '湘菜', rating: 4.4, price_range: '¥14-58', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '三层套鸡', cuisine_type: '湘菜', rating: 4.2, price_range: '¥12-44', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '长沙糕点', cuisine_type: '湘菜', rating: 4.3, price_range: '¥23-46', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '浏阳蒸菜', cuisine_type: '湘菜', rating: 4.4, price_range: '¥14-38', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '长沙盒饭', cuisine_type: '湘菜', rating: 4.6, price_range: '¥16-62', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
    { name: '湘西外婆菜', cuisine_type: '湘菜', rating: 4.2, price_range: '¥22-44', is_featured: false, tags: ['特色'], description: '长沙特色美食' },
  ])

  // 成都美食 (30个)
  addCityFoods('成都', [
    { name: '麻辣香锅', cuisine_type: '川菜', rating: 4.6, price_range: '¥26-62', is_featured: true, tags: ['必吃', '特色'], description: '成都特色美食' },
    { name: '麻婆豆腐', cuisine_type: '川菜', rating: 4.2, price_range: '¥12-44', is_featured: true, tags: ['必吃', '特色'], description: '成都特色美食' },
    { name: '四川火锅', cuisine_type: '川菜', rating: 4.7, price_range: '¥17-44', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '宫保鸡丁', cuisine_type: '川菜', rating: 4.8, price_range: '¥18-56', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '水煮牛肉', cuisine_type: '川菜', rating: 4.1, price_range: '¥21-42', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '回锅肉', cuisine_type: '川菜', rating: 4.6, price_range: '¥16-42', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '夫妻肺片', cuisine_type: '川菜', rating: 4.8, price_range: '¥18-46', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '担担面', cuisine_type: '川菜', rating: 4.5, price_range: '¥25-60', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '串串香', cuisine_type: '川菜', rating: 4.1, price_range: '¥21-42', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '龙抄手', cuisine_type: '川菜', rating: 4.5, price_range: '¥25-50', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '钟水饺', cuisine_type: '川菜', rating: 4.5, price_range: '¥25-70', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '赖汤圆', cuisine_type: '川菜', rating: 4.9, price_range: '¥29-58', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '酸辣粉', cuisine_type: '川菜', rating: 4.3, price_range: '¥23-66', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '冰粉', cuisine_type: '川菜', rating: 4.4, price_range: '¥14-58', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '三大炮', cuisine_type: '川菜', rating: 4.9, price_range: '¥29-78', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '兔头', cuisine_type: '川菜', rating: 4.4, price_range: '¥14-48', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '肥肠粉', cuisine_type: '川菜', rating: 4.0, price_range: '¥20-60', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '叶儿粑', cuisine_type: '川菜', rating: 4.6, price_range: '¥26-72', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '艾窝窝', cuisine_type: '川菜', rating: 4.0, price_range: '¥10-50', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '樟茶鸭', cuisine_type: '川菜', rating: 4.9, price_range: '¥29-58', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '钵钵鸡', cuisine_type: '川菜', rating: 4.1, price_range: '¥11-32', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '蛋烘糕', cuisine_type: '川菜', rating: 4.1, price_range: '¥11-52', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '糖油果子', cuisine_type: '川菜', rating: 4.8, price_range: '¥28-76', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '甜水面', cuisine_type: '川菜', rating: 4.1, price_range: '¥21-62', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '红油水饺', cuisine_type: '川菜', rating: 4.9, price_range: '¥19-48', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '冒菜', cuisine_type: '川菜', rating: 4.7, price_range: '¥27-54', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '冷锅串串', cuisine_type: '川菜', rating: 4.4, price_range: '¥14-38', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '成都烧烤', cuisine_type: '川菜', rating: 4.5, price_range: '¥15-50', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '三哥田螺', cuisine_type: '川菜', rating: 4.7, price_range: '¥27-54', is_featured: false, tags: ['特色'], description: '成都特色美食' },
    { name: '肖家河家常面', cuisine_type: '川菜', rating: 4.9, price_range: '¥19-58', is_featured: false, tags: ['特色'], description: '成都特色美食' },
  ])

  // 重庆美食 (30个)
  addCityFoods('重庆', [
    { name: '重庆火锅', cuisine_type: '川菜', rating: 4.2, price_range: '¥12-54', is_featured: true, tags: ['必吃', '特色'], description: '重庆特色美食' },
    { name: '重庆小面', cuisine_type: '川菜', rating: 4.8, price_range: '¥18-66', is_featured: true, tags: ['必吃', '特色'], description: '重庆特色美食' },
    { name: '酸辣粉', cuisine_type: '川菜', rating: 4.3, price_range: '¥23-66', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '麻辣香锅', cuisine_type: '川菜', rating: 4.6, price_range: '¥26-62', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '毛血旺', cuisine_type: '川菜', rating: 4.6, price_range: '¥16-52', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '水煮鱼', cuisine_type: '川菜', rating: 4.0, price_range: '¥20-50', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '辣子鸡', cuisine_type: '川菜', rating: 4.5, price_range: '¥15-60', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '豆花饭', cuisine_type: '川菜', rating: 4.1, price_range: '¥21-52', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '重庆粑粑', cuisine_type: '川菜', rating: 4.5, price_range: '¥15-40', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '糍粑', cuisine_type: '川菜', rating: 4.2, price_range: '¥22-64', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '流水席', cuisine_type: '川菜', rating: 4.8, price_range: '¥18-66', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '八宝饭', cuisine_type: '川菜', rating: 4.9, price_range: '¥29-78', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '酸萝卜面', cuisine_type: '川菜', rating: 4.6, price_range: '¥26-62', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '冰粉', cuisine_type: '川菜', rating: 4.4, price_range: '¥14-58', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '凉粉', cuisine_type: '川菜', rating: 4.1, price_range: '¥21-62', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '留香鸡', cuisine_type: '川菜', rating: 4.3, price_range: '¥23-66', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '串串香', cuisine_type: '川菜', rating: 4.1, price_range: '¥21-42', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '板凳面', cuisine_type: '川菜', rating: 4.2, price_range: '¥12-54', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '豌杂面', cuisine_type: '川菜', rating: 4.3, price_range: '¥23-56', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '烧麦', cuisine_type: '川菜', rating: 4.5, price_range: '¥25-60', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '鸡杂', cuisine_type: '川菜', rating: 4.3, price_range: '¥13-36', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '烤鱼', cuisine_type: '川菜', rating: 4.9, price_range: '¥19-48', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '黔江鸡杂', cuisine_type: '川菜', rating: 4.1, price_range: '¥21-52', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '涪陵榨菜', cuisine_type: '川菜', rating: 4.2, price_range: '¥22-64', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '合川桃片', cuisine_type: '川菜', rating: 4.9, price_range: '¥19-58', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '江津米花糖', cuisine_type: '川菜', rating: 4.3, price_range: '¥13-46', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '陈麻花', cuisine_type: '川菜', rating: 4.7, price_range: '¥27-74', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '山城小汤圆', cuisine_type: '川菜', rating: 4.3, price_range: '¥23-66', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '毛凉粉', cuisine_type: '川菜', rating: 4.8, price_range: '¥28-76', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
    { name: '重庆回锅肉', cuisine_type: '川菜', rating: 4.4, price_range: '¥14-48', is_featured: false, tags: ['特色'], description: '重庆特色美食' },
  ])

  // 大理美食 (30个)
  addCityFoods('大理', [
    { name: '烤乳扇', cuisine_type: '云南菜', rating: 4.6, price_range: '¥16-42', is_featured: true, tags: ['必吃', '特色'], description: '大理特色美食' },
    { name: '大理生皮', cuisine_type: '云南菜', rating: 4.7, price_range: '¥17-64', is_featured: true, tags: ['必吃', '特色'], description: '大理特色美食' },
    { name: '大理酸辣鱼', cuisine_type: '云南菜', rating: 4.9, price_range: '¥29-58', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '喜洲粑粑', cuisine_type: '云南菜', rating: 4.4, price_range: '¥24-58', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '凉鸡米线', cuisine_type: '云南菜', rating: 4.1, price_range: '¥11-32', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '砂锅鱼', cuisine_type: '云南菜', rating: 4.2, price_range: '¥22-54', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '巍山耙肉饵丝', cuisine_type: '云南菜', rating: 4.0, price_range: '¥10-50', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '雕梅扣肉', cuisine_type: '云南菜', rating: 4.4, price_range: '¥14-38', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '永平黄焖鸡', cuisine_type: '云南菜', rating: 4.5, price_range: '¥25-60', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '雕梅酒', cuisine_type: '云南菜', rating: 4.7, price_range: '¥27-64', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '白族土八碗', cuisine_type: '云南菜', rating: 4.2, price_range: '¥12-34', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '大理洱海砂锅鱼', cuisine_type: '云南菜', rating: 4.2, price_range: '¥12-44', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '剑川八大碗', cuisine_type: '云南菜', rating: 4.7, price_range: '¥27-54', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '云龙诺邓火腿', cuisine_type: '云南菜', rating: 4.9, price_range: '¥19-58', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '南涧锅巴油粉', cuisine_type: '云南菜', rating: 4.7, price_range: '¥27-54', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '漾濞卷粉', cuisine_type: '云南菜', rating: 4.4, price_range: '¥24-58', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '宾川韭菜腌菜', cuisine_type: '云南菜', rating: 4.5, price_range: '¥15-40', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '烤饵块', cuisine_type: '云南菜', rating: 4.6, price_range: '¥26-52', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '大理凉粉', cuisine_type: '云南菜', rating: 4.1, price_range: '¥11-42', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '耙肉饵丝', cuisine_type: '云南菜', rating: 4.3, price_range: '¥23-66', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '大理锅锅菜', cuisine_type: '云南菜', rating: 4.9, price_range: '¥19-58', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '白族三道茶', cuisine_type: '云南菜', rating: 4.1, price_range: '¥21-42', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '大理梅子', cuisine_type: '云南菜', rating: 4.9, price_range: '¥19-58', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '双乳扇', cuisine_type: '云南菜', rating: 4.4, price_range: '¥14-58', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '大理黑桂鱼', cuisine_type: '云南菜', rating: 4.8, price_range: '¥18-66', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '苍山雪鱼', cuisine_type: '云南菜', rating: 4.5, price_range: '¥25-70', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '大理雪茶', cuisine_type: '云南菜', rating: 4.7, price_range: '¥17-54', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '西瓜酱', cuisine_type: '云南菜', rating: 4.8, price_range: '¥18-46', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '大理鱼粥', cuisine_type: '云南菜', rating: 4.4, price_range: '¥14-38', is_featured: false, tags: ['特色'], description: '大理特色美食' },
    { name: '羊奶乳扇', cuisine_type: '云南菜', rating: 4.4, price_range: '¥14-48', is_featured: false, tags: ['特色'], description: '大理特色美食' },
  ])

  // 广州美食 (30个)
  addCityFoods('广州', [
    { name: '虾饺', cuisine_type: '粤菜', rating: 4.5, price_range: '¥25-70', is_featured: true, tags: ['必吃', '特色'], description: '广州特色美食' },
    { name: '叉烧包', cuisine_type: '粤菜', rating: 4.6, price_range: '¥26-62', is_featured: true, tags: ['必吃', '特色'], description: '广州特色美食' },
    { name: '蛋挞', cuisine_type: '粤菜', rating: 4.0, price_range: '¥10-50', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '马拉糕', cuisine_type: '粤菜', rating: 4.6, price_range: '¥16-52', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '干蒸烧卖', cuisine_type: '粤菜', rating: 4.0, price_range: '¥10-30', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '奶黄包', cuisine_type: '粤菜', rating: 4.1, price_range: '¥21-42', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '陈醋凤爪', cuisine_type: '粤菜', rating: 4.2, price_range: '¥12-34', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '沙爹金钱肚', cuisine_type: '粤菜', rating: 4.2, price_range: '¥22-44', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '红米肠', cuisine_type: '粤菜', rating: 4.7, price_range: '¥17-44', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '艇仔粥', cuisine_type: '粤菜', rating: 4.5, price_range: '¥25-50', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '肠粉', cuisine_type: '粤菜', rating: 4.0, price_range: '¥20-40', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '白切鸡', cuisine_type: '粤菜', rating: 4.5, price_range: '¥15-60', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '烧鹅', cuisine_type: '粤菜', rating: 4.8, price_range: '¥18-56', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '腊肠', cuisine_type: '粤菜', rating: 4.4, price_range: '¥24-58', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '卤肉饭', cuisine_type: '粤菜', rating: 4.3, price_range: '¥23-66', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '双皮奶', cuisine_type: '粤菜', rating: 4.5, price_range: '¥15-40', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '姜撞奶', cuisine_type: '粤菜', rating: 4.4, price_range: '¥14-58', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '云吞面', cuisine_type: '粤菜', rating: 4.2, price_range: '¥22-44', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '生滚粥', cuisine_type: '粤菜', rating: 4.8, price_range: '¥28-66', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '凉茶', cuisine_type: '粤菜', rating: 4.0, price_range: '¥10-30', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '及第粥', cuisine_type: '粤菜', rating: 4.8, price_range: '¥28-76', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '萝卜牛杂', cuisine_type: '粤菜', rating: 4.0, price_range: '¥20-50', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '鸡仔饼', cuisine_type: '粤菜', rating: 4.0, price_range: '¥20-50', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '老婆饼', cuisine_type: '粤菜', rating: 4.0, price_range: '¥20-60', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '广式月饼', cuisine_type: '粤菜', rating: 4.7, price_range: '¥17-64', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '马蹄糕', cuisine_type: '粤菜', rating: 4.2, price_range: '¥12-34', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '伦教糕', cuisine_type: '粤菜', rating: 4.0, price_range: '¥10-50', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '沙河粉', cuisine_type: '粤菜', rating: 4.4, price_range: '¥14-38', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '煲仔饭', cuisine_type: '粤菜', rating: 4.3, price_range: '¥23-66', is_featured: false, tags: ['特色'], description: '广州特色美食' },
    { name: '豉油鸡', cuisine_type: '粤菜', rating: 4.0, price_range: '¥20-50', is_featured: false, tags: ['特色'], description: '广州特色美食' },
  ])

  // 桂林美食 (29个)
  addCityFoods('桂林', [
    { name: '桂林米粉', cuisine_type: '桂菜', rating: 4.2, price_range: '¥22-64', is_featured: true, tags: ['必吃', '特色'], description: '桂林特色美食' },
    { name: '荔浦扣肉', cuisine_type: '桂菜', rating: 4.5, price_range: '¥15-50', is_featured: true, tags: ['必吃', '特色'], description: '桂林特色美食' },
    { name: '阳朔啤酒鱼', cuisine_type: '桂菜', rating: 4.6, price_range: '¥16-42', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '全州醋血鸭', cuisine_type: '桂菜', rating: 4.6, price_range: '¥26-52', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '平乐十八酿', cuisine_type: '桂菜', rating: 4.7, price_range: '¥17-64', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '桂林马肉米粉', cuisine_type: '桂菜', rating: 4.2, price_range: '¥12-34', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '全州禾花鱼', cuisine_type: '桂菜', rating: 4.5, price_range: '¥15-40', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '阳朔田螺酿', cuisine_type: '桂菜', rating: 4.1, price_range: '¥21-42', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '恭城油茶', cuisine_type: '桂菜', rating: 4.1, price_range: '¥21-52', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '龙脊竹筒饭', cuisine_type: '桂菜', rating: 4.4, price_range: '¥24-48', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '兴安白果', cuisine_type: '桂菜', rating: 4.6, price_range: '¥16-62', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '阳朔糍粑', cuisine_type: '桂菜', rating: 4.1, price_range: '¥11-32', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '灌阳红薯粉', cuisine_type: '桂菜', rating: 4.7, price_range: '¥17-64', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '资源竹笋', cuisine_type: '桂菜', rating: 4.0, price_range: '¥20-50', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '永福罗汉果', cuisine_type: '桂菜', rating: 4.9, price_range: '¥19-58', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '平乐沙田柚', cuisine_type: '桂菜', rating: 4.3, price_range: '¥23-56', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '恭城月柿', cuisine_type: '桂菜', rating: 4.3, price_range: '¥13-46', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '荔浦芋', cuisine_type: '桂菜', rating: 4.9, price_range: '¥19-58', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '桂林三花酒', cuisine_type: '桂菜', rating: 4.1, price_range: '¥11-32', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '桂林田螺', cuisine_type: '桂菜', rating: 4.5, price_range: '¥15-50', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '马蹄糕', cuisine_type: '桂菜', rating: 4.2, price_range: '¥12-34', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '桂花糕', cuisine_type: '桂菜', rating: 4.6, price_range: '¥26-72', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '尼姑素面', cuisine_type: '桂菜', rating: 4.5, price_range: '¥15-60', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '桂林松糕', cuisine_type: '桂菜', rating: 4.9, price_range: '¥19-58', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '桂林水糍粑', cuisine_type: '桂菜', rating: 4.5, price_range: '¥25-50', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '桂林腐乳', cuisine_type: '桂菜', rating: 4.4, price_range: '¥24-68', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '桂林辣椒酱', cuisine_type: '桂菜', rating: 4.6, price_range: '¥16-62', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '阳朔啤酒', cuisine_type: '桂菜', rating: 4.3, price_range: '¥23-66', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
    { name: '罗汉果', cuisine_type: '桂菜', rating: 4.8, price_range: '¥28-66', is_featured: false, tags: ['特色'], description: '桂林特色美食' },
  ])

  // 杭州美食 (29个)
  addCityFoods('杭州', [
    { name: '西湖醋鱼', cuisine_type: '浙菜', rating: 4.2, price_range: '¥22-44', is_featured: true, tags: ['必吃', '特色'], description: '杭州特色美食' },
    { name: '片儿川', cuisine_type: '浙菜', rating: 4.8, price_range: '¥18-46', is_featured: true, tags: ['必吃', '特色'], description: '杭州特色美食' },
    { name: '葱包桧儿', cuisine_type: '浙菜', rating: 4.6, price_range: '¥16-52', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '宋嫂鱼羹', cuisine_type: '浙菜', rating: 4.1, price_range: '¥21-52', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '干炸响铃', cuisine_type: '浙菜', rating: 4.5, price_range: '¥25-50', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '荷叶粉蒸肉', cuisine_type: '浙菜', rating: 4.2, price_range: '¥12-34', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '小鸡酥', cuisine_type: '浙菜', rating: 4.1, price_range: '¥21-62', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '南宋定胜糕', cuisine_type: '浙菜', rating: 4.2, price_range: '¥12-44', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '知味小笼', cuisine_type: '浙菜', rating: 4.6, price_range: '¥26-72', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '吴山酥油饼', cuisine_type: '浙菜', rating: 4.6, price_range: '¥16-62', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '杭州猫耳朵', cuisine_type: '浙菜', rating: 4.8, price_range: '¥18-56', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '麻球王', cuisine_type: '浙菜', rating: 4.9, price_range: '¥29-78', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '龙井虾仁', cuisine_type: '浙菜', rating: 4.5, price_range: '¥15-60', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '叫花鸡', cuisine_type: '浙菜', rating: 4.3, price_range: '¥23-56', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '白切鸡', cuisine_type: '浙菜', rating: 4.5, price_range: '¥15-60', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '糖桂花', cuisine_type: '浙菜', rating: 4.9, price_range: '¥19-68', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '绿豆糕', cuisine_type: '浙菜', rating: 4.9, price_range: '¥19-48', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '粢饭团', cuisine_type: '浙菜', rating: 4.9, price_range: '¥19-68', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '油条', cuisine_type: '浙菜', rating: 4.1, price_range: '¥11-32', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '西湖莼菜汤', cuisine_type: '浙菜', rating: 4.8, price_range: '¥18-46', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '虾爆鳝面', cuisine_type: '浙菜', rating: 4.3, price_range: '¥13-56', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '西湖藕粉', cuisine_type: '浙菜', rating: 4.5, price_range: '¥15-50', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '荷花酥', cuisine_type: '浙菜', rating: 4.4, price_range: '¥14-38', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '定胜糕', cuisine_type: '浙菜', rating: 4.3, price_range: '¥23-56', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '醋鱼', cuisine_type: '浙菜', rating: 4.5, price_range: '¥15-60', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '东坡肉', cuisine_type: '浙菜', rating: 4.3, price_range: '¥13-56', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '杭州小笼', cuisine_type: '浙菜', rating: 4.2, price_range: '¥22-64', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '杭州油条', cuisine_type: '浙菜', rating: 4.2, price_range: '¥22-44', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
    { name: '杭州粢饭', cuisine_type: '浙菜', rating: 4.6, price_range: '¥16-52', is_featured: false, tags: ['特色'], description: '杭州特色美食' },
  ])

  // 黄山美食 (30个)
  addCityFoods('黄山', [
    { name: '徽州臭鳜鱼', cuisine_type: '徽菜', rating: 4.9, price_range: '¥29-68', is_featured: true, tags: ['必吃', '特色'], description: '黄山特色美食' },
    { name: '徽州毛豆腐', cuisine_type: '徽菜', rating: 4.5, price_range: '¥25-50', is_featured: true, tags: ['必吃', '特色'], description: '黄山特色美食' },
    { name: '黄山烧饼', cuisine_type: '徽菜', rating: 4.7, price_range: '¥17-44', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '徽州刀板香', cuisine_type: '徽菜', rating: 4.7, price_range: '¥17-44', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '问政山笋', cuisine_type: '徽菜', rating: 4.4, price_range: '¥24-48', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '黄山双石', cuisine_type: '徽菜', rating: 4.1, price_range: '¥11-52', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '五城茶干', cuisine_type: '徽菜', rating: 4.7, price_range: '¥27-54', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '黄山炖鸽', cuisine_type: '徽菜', rating: 4.7, price_range: '¥17-44', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '徽州圆子', cuisine_type: '徽菜', rating: 4.9, price_range: '¥29-78', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '黄山蕨菜', cuisine_type: '徽菜', rating: 4.5, price_range: '¥15-40', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '红烧臭鳜鱼', cuisine_type: '徽菜', rating: 4.4, price_range: '¥14-58', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '问政山笋煲', cuisine_type: '徽菜', rating: 4.2, price_range: '¥22-54', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '胡适一品锅', cuisine_type: '徽菜', rating: 4.3, price_range: '¥13-36', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '火腿炖甲鱼', cuisine_type: '徽菜', rating: 4.1, price_range: '¥11-52', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '沙地马蹄鳖', cuisine_type: '徽菜', rating: 4.3, price_range: '¥23-56', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '雪天牛尾狸', cuisine_type: '徽菜', rating: 4.9, price_range: '¥19-48', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '石耳炖石鸡', cuisine_type: '徽菜', rating: 4.8, price_range: '¥18-46', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '挞粿', cuisine_type: '徽菜', rating: 4.5, price_range: '¥15-60', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '毛豆腐', cuisine_type: '徽菜', rating: 4.2, price_range: '¥12-34', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '油煎毛豆腐', cuisine_type: '徽菜', rating: 4.4, price_range: '¥14-38', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '徽州裹粽', cuisine_type: '徽菜', rating: 4.8, price_range: '¥28-76', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '徽州状元饭', cuisine_type: '徽菜', rating: 4.5, price_range: '¥15-50', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '虎皮毛豆腐', cuisine_type: '徽菜', rating: 4.9, price_range: '¥29-78', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '徽州石鸡', cuisine_type: '徽菜', rating: 4.7, price_range: '¥17-44', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '徽州桃脂烧肉', cuisine_type: '徽菜', rating: 4.0, price_range: '¥20-40', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '黄山炖鸽', cuisine_type: '徽菜', rating: 4.7, price_range: '¥17-44', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '徽州蒸鸡', cuisine_type: '徽菜', rating: 4.1, price_range: '¥11-52', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '黟县腊八豆腐', cuisine_type: '徽菜', rating: 4.5, price_range: '¥25-50', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '徽州臭豆腐', cuisine_type: '徽菜', rating: 4.8, price_range: '¥18-46', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
    { name: '黄山猕猴桃', cuisine_type: '徽菜', rating: 4.9, price_range: '¥29-78', is_featured: false, tags: ['特色'], description: '黄山特色美食' },
  ])

  // 九寨沟美食 (30个)
  addCityFoods('九寨沟', [
    { name: '九寨柿饼', cuisine_type: '藏菜', rating: 4.9, price_range: '¥29-58', is_featured: true, tags: ['必吃', '特色'], description: '九寨沟特色美食' },
    { name: '酸菜面块', cuisine_type: '藏菜', rating: 4.9, price_range: '¥29-58', is_featured: true, tags: ['必吃', '特色'], description: '九寨沟特色美食' },
    { name: '洋芋糍粑', cuisine_type: '藏菜', rating: 4.8, price_range: '¥18-66', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '酥油茶', cuisine_type: '藏菜', rating: 4.3, price_range: '¥23-46', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '藏族血肠', cuisine_type: '藏菜', rating: 4.1, price_range: '¥21-52', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '牦牛肉干', cuisine_type: '藏菜', rating: 4.7, price_range: '¥17-44', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '奶渣包子', cuisine_type: '藏菜', rating: 4.6, price_range: '¥26-72', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '藏民奶制品', cuisine_type: '藏菜', rating: 4.3, price_range: '¥23-46', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '荞麦面食', cuisine_type: '藏菜', rating: 4.3, price_range: '¥13-36', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '豌杂面', cuisine_type: '藏菜', rating: 4.3, price_range: '¥23-56', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '糌粑', cuisine_type: '藏菜', rating: 4.5, price_range: '¥15-60', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '牦牛肉', cuisine_type: '藏菜', rating: 4.6, price_range: '¥26-52', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '荞麦饼', cuisine_type: '藏菜', rating: 4.8, price_range: '¥28-76', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '青稞酒', cuisine_type: '藏菜', rating: 4.5, price_range: '¥25-70', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '酸奶', cuisine_type: '藏菜', rating: 4.5, price_range: '¥15-60', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '奶茶', cuisine_type: '藏菜', rating: 4.5, price_range: '¥15-40', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '羊肉汤', cuisine_type: '藏菜', rating: 4.9, price_range: '¥29-68', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '牛肉汤', cuisine_type: '藏菜', rating: 4.7, price_range: '¥27-74', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '面条', cuisine_type: '藏菜', rating: 4.2, price_range: '¥22-54', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '米饭', cuisine_type: '藏菜', rating: 4.7, price_range: '¥17-44', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '手抓肉', cuisine_type: '藏菜', rating: 4.9, price_range: '¥29-78', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '烤全羊', cuisine_type: '藏菜', rating: 4.9, price_range: '¥19-68', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '藏式火锅', cuisine_type: '藏菜', rating: 4.2, price_range: '¥22-64', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '人参果饭', cuisine_type: '藏菜', rating: 4.8, price_range: '¥28-66', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '虫草鸭', cuisine_type: '藏菜', rating: 4.1, price_range: '¥11-32', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '九寨黄瓜', cuisine_type: '藏菜', rating: 4.9, price_range: '¥29-78', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '羊肉泡馍', cuisine_type: '藏菜', rating: 4.5, price_range: '¥25-70', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '风干牛肉', cuisine_type: '藏菜', rating: 4.1, price_range: '¥11-42', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '奶皮', cuisine_type: '藏菜', rating: 4.0, price_range: '¥10-40', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
    { name: '油炸酸奶', cuisine_type: '藏菜', rating: 4.2, price_range: '¥22-44', is_featured: false, tags: ['特色'], description: '九寨沟特色美食' },
  ])

  // 丽江美食 (30个)
  addCityFoods('丽江', [
    { name: '腊排骨火锅', cuisine_type: '云南菜', rating: 4.3, price_range: '¥13-56', is_featured: true, tags: ['必吃', '特色'], description: '丽江特色美食' },
    { name: '水性杨花', cuisine_type: '云南菜', rating: 4.3, price_range: '¥13-56', is_featured: true, tags: ['必吃', '特色'], description: '丽江特色美食' },
    { name: '丽江粑粑', cuisine_type: '云南菜', rating: 4.4, price_range: '¥14-48', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '纳西烤肉', cuisine_type: '云南菜', rating: 4.6, price_range: '¥26-52', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '鸡豆凉粉', cuisine_type: '云南菜', rating: 4.5, price_range: '¥15-50', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '包浆豆腐', cuisine_type: '云南菜', rating: 4.2, price_range: '¥12-54', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '黑山羊火锅', cuisine_type: '云南菜', rating: 4.2, price_range: '¥22-44', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '松茸', cuisine_type: '云南菜', rating: 4.0, price_range: '¥20-50', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '纳西烤鱼', cuisine_type: '云南菜', rating: 4.8, price_range: '¥18-56', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '洋芋鸡', cuisine_type: '云南菜', rating: 4.8, price_range: '¥28-66', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '汽锅鸡', cuisine_type: '云南菜', rating: 4.2, price_range: '¥22-64', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '过桥米线', cuisine_type: '云南菜', rating: 4.1, price_range: '¥21-42', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '酸汤鱼', cuisine_type: '云南菜', rating: 4.9, price_range: '¥29-78', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '凉粉', cuisine_type: '云南菜', rating: 4.1, price_range: '¥21-62', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '米线', cuisine_type: '云南菜', rating: 4.5, price_range: '¥25-70', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '饵丝', cuisine_type: '云南菜', rating: 4.2, price_range: '¥22-64', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '小白菜', cuisine_type: '云南菜', rating: 4.9, price_range: '¥19-58', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '青菜', cuisine_type: '云南菜', rating: 4.2, price_range: '¥22-64', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '土豆', cuisine_type: '云南菜', rating: 4.5, price_range: '¥15-60', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '红薯', cuisine_type: '云南菜', rating: 4.2, price_range: '¥12-44', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '米灌肠', cuisine_type: '云南菜', rating: 4.2, price_range: '¥22-54', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '酥油茶', cuisine_type: '云南菜', rating: 4.3, price_range: '¥23-46', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '雪茶', cuisine_type: '云南菜', rating: 4.2, price_range: '¥22-44', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '螺旋藻', cuisine_type: '云南菜', rating: 4.3, price_range: '¥13-36', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '东巴烤鱼', cuisine_type: '云南菜', rating: 4.6, price_range: '¥16-42', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '三文鱼', cuisine_type: '云南菜', rating: 4.1, price_range: '¥21-42', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '野生菌', cuisine_type: '云南菜', rating: 4.5, price_range: '¥25-50', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '鲜花饼', cuisine_type: '云南菜', rating: 4.9, price_range: '¥29-78', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '丽江腌菜', cuisine_type: '云南菜', rating: 4.9, price_range: '¥29-58', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
    { name: '丽江酒', cuisine_type: '云南菜', rating: 4.4, price_range: '¥24-58', is_featured: false, tags: ['特色'], description: '丽江特色美食' },
  ])

  // 南京美食 (30个)
  addCityFoods('南京', [
    { name: '鸭血粉丝汤', cuisine_type: '苏菜', rating: 4.2, price_range: '¥12-34', is_featured: true, tags: ['必吃', '特色'], description: '南京特色美食' },
    { name: '牛肉锅贴', cuisine_type: '苏菜', rating: 4.7, price_range: '¥27-64', is_featured: true, tags: ['必吃', '特色'], description: '南京特色美食' },
    { name: '盐水鸭', cuisine_type: '苏菜', rating: 4.3, price_range: '¥13-36', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '南京烤鸭', cuisine_type: '苏菜', rating: 4.4, price_range: '¥24-68', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '皮肚面', cuisine_type: '苏菜', rating: 4.6, price_range: '¥26-72', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '鸡鸣汤包', cuisine_type: '苏菜', rating: 4.7, price_range: '¥27-74', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '红枣糕', cuisine_type: '苏菜', rating: 4.1, price_range: '¥11-32', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '秦淮八绝', cuisine_type: '苏菜', rating: 4.8, price_range: '¥28-56', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '黄桥烧饼', cuisine_type: '苏菜', rating: 4.7, price_range: '¥17-54', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '开洋干丝', cuisine_type: '苏菜', rating: 4.9, price_range: '¥19-68', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '牛肉汤', cuisine_type: '苏菜', rating: 4.7, price_range: '¥27-74', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '臭豆腐', cuisine_type: '苏菜', rating: 4.1, price_range: '¥21-52', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '麻辣小龙虾', cuisine_type: '苏菜', rating: 4.7, price_range: '¥27-54', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '糖芋苗', cuisine_type: '苏菜', rating: 4.4, price_range: '¥14-48', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '赤豆元宵', cuisine_type: '苏菜', rating: 4.5, price_range: '¥15-40', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '梅花糕', cuisine_type: '苏菜', rating: 4.8, price_range: '¥18-66', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '酥烧饼', cuisine_type: '苏菜', rating: 4.0, price_range: '¥10-50', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '菜包', cuisine_type: '苏菜', rating: 4.5, price_range: '¥25-50', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '肉包', cuisine_type: '苏菜', rating: 4.9, price_range: '¥29-78', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '美龄粥', cuisine_type: '苏菜', rating: 4.0, price_range: '¥20-50', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '桂花糕', cuisine_type: '苏菜', rating: 4.6, price_range: '¥26-72', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '如意回卤干', cuisine_type: '苏菜', rating: 4.2, price_range: '¥22-54', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '什锦豆腐涝', cuisine_type: '苏菜', rating: 4.3, price_range: '¥23-56', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '状元豆', cuisine_type: '苏菜', rating: 4.3, price_range: '¥13-56', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '旺鸡蛋', cuisine_type: '苏菜', rating: 4.6, price_range: '¥16-62', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '活珠子', cuisine_type: '苏菜', rating: 4.0, price_range: '¥10-30', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '洪蓝玉带糕', cuisine_type: '苏菜', rating: 4.2, price_range: '¥12-44', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '东坝豆腐干', cuisine_type: '苏菜', rating: 4.7, price_range: '¥27-64', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '南京鸭血粉丝', cuisine_type: '苏菜', rating: 4.1, price_range: '¥11-32', is_featured: false, tags: ['特色'], description: '南京特色美食' },
    { name: '鸭血粉丝', cuisine_type: '苏菜', rating: 4.9, price_range: '¥29-68', is_featured: false, tags: ['特色'], description: '南京特色美食' },
  ])

  // 青岛美食 (30个)
  addCityFoods('青岛', [
    { name: '辣炒蛤蜊', cuisine_type: '鲁菜', rating: 4.5, price_range: '¥25-60', is_featured: true, tags: ['必吃', '特色'], description: '青岛特色美食' },
    { name: '鲅鱼水饺', cuisine_type: '鲁菜', rating: 4.4, price_range: '¥24-58', is_featured: true, tags: ['必吃', '特色'], description: '青岛特色美食' },
    { name: '流亭猪蹄', cuisine_type: '鲁菜', rating: 4.1, price_range: '¥11-42', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '海肠捞饭', cuisine_type: '鲁菜', rating: 4.1, price_range: '¥21-52', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '青岛脂渣', cuisine_type: '鲁菜', rating: 4.1, price_range: '¥21-52', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '李村戳子肉', cuisine_type: '鲁菜', rating: 4.6, price_range: '¥26-72', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '海菜凉粉', cuisine_type: '鲁菜', rating: 4.4, price_range: '¥24-58', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '排骨米饭', cuisine_type: '鲁菜', rating: 4.2, price_range: '¥22-54', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '青岛锅贴', cuisine_type: '鲁菜', rating: 4.9, price_range: '¥19-58', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '崂山菇炖鸡', cuisine_type: '鲁菜', rating: 4.7, price_range: '¥27-54', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '鲍鱼', cuisine_type: '鲁菜', rating: 4.9, price_range: '¥19-48', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '海参', cuisine_type: '鲁菜', rating: 4.5, price_range: '¥25-60', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '大虾', cuisine_type: '鲁菜', rating: 4.7, price_range: '¥27-64', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '海带', cuisine_type: '鲁菜', rating: 4.0, price_range: '¥20-50', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '黄花鱼', cuisine_type: '鲁菜', rating: 4.6, price_range: '¥16-62', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '青岛大包', cuisine_type: '鲁菜', rating: 4.0, price_range: '¥10-50', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '油条', cuisine_type: '鲁菜', rating: 4.1, price_range: '¥11-32', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '豆腐脑', cuisine_type: '鲁菜', rating: 4.7, price_range: '¥17-54', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '烧饼', cuisine_type: '鲁菜', rating: 4.2, price_range: '¥22-54', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '煎饼果子', cuisine_type: '鲁菜', rating: 4.7, price_range: '¥27-64', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '海鲜大咖', cuisine_type: '鲁菜', rating: 4.3, price_range: '¥13-46', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '烤鱿鱼', cuisine_type: '鲁菜', rating: 4.8, price_range: '¥28-56', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '海鲜馄饨', cuisine_type: '鲁菜', rating: 4.3, price_range: '¥23-56', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '酱猪蹄', cuisine_type: '鲁菜', rating: 4.4, price_range: '¥14-58', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '葱油饼', cuisine_type: '鲁菜', rating: 4.3, price_range: '¥13-36', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '海鲜疙瘩汤', cuisine_type: '鲁菜', rating: 4.0, price_range: '¥20-60', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '炸蛎黄', cuisine_type: '鲁菜', rating: 4.5, price_range: '¥15-60', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '原壳鲍鱼', cuisine_type: '鲁菜', rating: 4.6, price_range: '¥26-62', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '肉末海参', cuisine_type: '鲁菜', rating: 4.0, price_range: '¥10-50', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
    { name: '青岛大包', cuisine_type: '鲁菜', rating: 4.0, price_range: '¥10-50', is_featured: false, tags: ['特色'], description: '青岛特色美食' },
  ])

  // 三亚美食 (29个)
  addCityFoods('三亚', [
    { name: '文昌鸡', cuisine_type: '海南菜', rating: 4.8, price_range: '¥18-46', is_featured: true, tags: ['必吃', '特色'], description: '三亚特色美食' },
    { name: '加积鸭', cuisine_type: '海南菜', rating: 4.2, price_range: '¥12-34', is_featured: true, tags: ['必吃', '特色'], description: '三亚特色美食' },
    { name: '和乐蟹', cuisine_type: '海南菜', rating: 4.2, price_range: '¥12-54', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '东山羊', cuisine_type: '海南菜', rating: 4.6, price_range: '¥26-52', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '抱罗粉', cuisine_type: '海南菜', rating: 4.4, price_range: '¥24-68', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '清补凉', cuisine_type: '海南菜', rating: 4.9, price_range: '¥29-68', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '海南粉', cuisine_type: '海南菜', rating: 4.4, price_range: '¥14-38', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '椰子饭', cuisine_type: '海南菜', rating: 4.3, price_range: '¥13-56', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '竹筒饭', cuisine_type: '海南菜', rating: 4.6, price_range: '¥26-62', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '黑毛猪', cuisine_type: '海南菜', rating: 4.7, price_range: '¥27-64', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '海南海胆', cuisine_type: '海南菜', rating: 4.5, price_range: '¥25-70', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '龙虾', cuisine_type: '海南菜', rating: 4.3, price_range: '¥23-66', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '扇贝', cuisine_type: '海南菜', rating: 4.0, price_range: '¥20-40', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '海蜇', cuisine_type: '海南菜', rating: 4.3, price_range: '¥13-46', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '鱼煲', cuisine_type: '海南菜', rating: 4.7, price_range: '¥27-54', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '羊栏酸鱼汤', cuisine_type: '海南菜', rating: 4.2, price_range: '¥22-54', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '黎家竹筒饭', cuisine_type: '海南菜', rating: 4.7, price_range: '¥17-54', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '海南腌面', cuisine_type: '海南菜', rating: 4.9, price_range: '¥19-48', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '鸡屎藤粑仔', cuisine_type: '海南菜', rating: 4.5, price_range: '¥25-60', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '红糖年糕', cuisine_type: '海南菜', rating: 4.2, price_range: '¥12-34', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '椰子冻', cuisine_type: '海南菜', rating: 4.5, price_range: '¥15-40', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '港门粉', cuisine_type: '海南菜', rating: 4.0, price_range: '¥10-50', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '藤桥排骨', cuisine_type: '海南菜', rating: 4.6, price_range: '¥16-62', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '荔枝木烤鸭', cuisine_type: '海南菜', rating: 4.7, price_range: '¥17-44', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '海鲜火锅', cuisine_type: '海南菜', rating: 4.6, price_range: '¥16-52', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '椰奶清补凉', cuisine_type: '海南菜', rating: 4.5, price_range: '¥15-40', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '黄流老鸭', cuisine_type: '海南菜', rating: 4.5, price_range: '¥25-60', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '海南大虾', cuisine_type: '海南菜', rating: 4.7, price_range: '¥27-54', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
    { name: '椰子鸡', cuisine_type: '海南菜', rating: 4.9, price_range: '¥29-68', is_featured: false, tags: ['特色'], description: '三亚特色美食' },
  ])

  // 上海美食 (30个)
  addCityFoods('上海', [
    { name: '小笼包', cuisine_type: '本帮菜', rating: 4.5, price_range: '¥15-40', is_featured: true, tags: ['必吃', '特色'], description: '上海特色美食' },
    { name: '生煎包', cuisine_type: '本帮菜', rating: 4.7, price_range: '¥17-64', is_featured: true, tags: ['必吃', '特色'], description: '上海特色美食' },
    { name: '本帮红烧肉', cuisine_type: '本帮菜', rating: 4.8, price_range: '¥28-76', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '油爆虾', cuisine_type: '本帮菜', rating: 4.0, price_range: '¥20-50', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '脆牛肉', cuisine_type: '本帮菜', rating: 4.4, price_range: '¥24-48', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '糟钵头', cuisine_type: '本帮菜', rating: 4.7, price_range: '¥17-44', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '开洋葱油拌面', cuisine_type: '本帮菜', rating: 4.8, price_range: '¥28-56', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '糖醋小排', cuisine_type: '本帮菜', rating: 4.9, price_range: '¥29-68', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '三黄鸡', cuisine_type: '本帮菜', rating: 4.0, price_range: '¥20-40', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '粢饭糕', cuisine_type: '本帮菜', rating: 4.1, price_range: '¥11-52', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '臭豆腐', cuisine_type: '本帮菜', rating: 4.1, price_range: '¥21-52', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '咖喱牛肉汤', cuisine_type: '本帮菜', rating: 4.9, price_range: '¥29-68', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '排骨年糕', cuisine_type: '本帮菜', rating: 4.7, price_range: '¥27-64', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '四喜烤麸', cuisine_type: '本帮菜', rating: 4.4, price_range: '¥24-58', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '上海香肠', cuisine_type: '本帮菜', rating: 4.6, price_range: '¥26-52', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '大馄饨', cuisine_type: '本帮菜', rating: 4.0, price_range: '¥10-40', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '上海青', cuisine_type: '本帮菜', rating: 4.7, price_range: '¥27-64', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '豆沙包', cuisine_type: '本帮菜', rating: 4.8, price_range: '¥18-66', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '绿豆糕', cuisine_type: '本帮菜', rating: 4.9, price_range: '¥19-48', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '擂沙汤圆', cuisine_type: '本帮菜', rating: 4.2, price_range: '¥12-34', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '蟹壳黄', cuisine_type: '本帮菜', rating: 4.8, price_range: '¥18-56', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '南翔小笼包', cuisine_type: '本帮菜', rating: 4.5, price_range: '¥15-40', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '鲜肉月饼', cuisine_type: '本帮菜', rating: 4.8, price_range: '¥18-56', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '梨膏糖', cuisine_type: '本帮菜', rating: 4.1, price_range: '¥21-62', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '五香豆', cuisine_type: '本帮菜', rating: 4.5, price_range: '¥15-60', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '高桥松饼', cuisine_type: '本帮菜', rating: 4.4, price_range: '¥14-48', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '条头糕', cuisine_type: '本帮菜', rating: 4.4, price_range: '¥24-48', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '油豆腐线粉汤', cuisine_type: '本帮菜', rating: 4.6, price_range: '¥26-52', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '沈大成糕点', cuisine_type: '本帮菜', rating: 4.0, price_range: '¥10-50', is_featured: false, tags: ['特色'], description: '上海特色美食' },
    { name: '国际饭店蝴蝶酥', cuisine_type: '本帮菜', rating: 4.2, price_range: '¥22-54', is_featured: false, tags: ['特色'], description: '上海特色美食' },
  ])

  // 深圳美食 (30个)
  addCityFoods('深圳', [
    { name: '光明乳鸽', cuisine_type: '粤菜', rating: 4.4, price_range: '¥24-58', is_featured: true, tags: ['必吃', '特色'], description: '深圳特色美食' },
    { name: '公明烧鹅', cuisine_type: '粤菜', rating: 4.8, price_range: '¥28-76', is_featured: true, tags: ['必吃', '特色'], description: '深圳特色美食' },
    { name: '深井烧鹅', cuisine_type: '粤菜', rating: 4.2, price_range: '¥12-54', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '沙井蚝', cuisine_type: '粤菜', rating: 4.3, price_range: '¥13-36', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '南头荔枝', cuisine_type: '粤菜', rating: 4.8, price_range: '¥28-66', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '福田云吞', cuisine_type: '粤菜', rating: 4.4, price_range: '¥14-58', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '罗湖肠粉', cuisine_type: '粤菜', rating: 4.3, price_range: '¥13-56', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '龙岗鸡', cuisine_type: '粤菜', rating: 4.5, price_range: '¥25-70', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '宝安腊鸭', cuisine_type: '粤菜', rating: 4.1, price_range: '¥21-62', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '盐田海鲜', cuisine_type: '粤菜', rating: 4.9, price_range: '¥29-78', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '大梅沙海鲜', cuisine_type: '粤菜', rating: 4.5, price_range: '¥15-60', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '小梅沙烧烤', cuisine_type: '粤菜', rating: 4.6, price_range: '¥26-72', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '春满园早茶', cuisine_type: '粤菜', rating: 4.6, price_range: '¥16-62', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '点都德', cuisine_type: '粤菜', rating: 4.5, price_range: '¥15-40', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '陶陶居', cuisine_type: '粤菜', rating: 4.5, price_range: '¥15-60', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '莲香楼', cuisine_type: '粤菜', rating: 4.4, price_range: '¥14-48', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '广州酒家', cuisine_type: '粤菜', rating: 4.0, price_range: '¥10-50', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '泮溪酒家', cuisine_type: '粤菜', rating: 4.0, price_range: '¥10-50', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '北园酒家', cuisine_type: '粤菜', rating: 4.3, price_range: '¥23-46', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '东江盐焗鸡', cuisine_type: '粤菜', rating: 4.7, price_range: '¥17-44', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '猪肚鸡', cuisine_type: '粤菜', rating: 4.4, price_range: '¥24-58', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '椰子鸡', cuisine_type: '粤菜', rating: 4.9, price_range: '¥29-68', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '潮汕牛肉火锅', cuisine_type: '粤菜', rating: 4.0, price_range: '¥10-40', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '广式早茶', cuisine_type: '粤菜', rating: 4.2, price_range: '¥22-54', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '肠粉', cuisine_type: '粤菜', rating: 4.0, price_range: '¥20-40', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '叉烧', cuisine_type: '粤菜', rating: 4.9, price_range: '¥29-68', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '烧鹅饭', cuisine_type: '粤菜', rating: 4.7, price_range: '¥17-44', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '港式奶茶', cuisine_type: '粤菜', rating: 4.3, price_range: '¥13-36', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '鸡蛋仔', cuisine_type: '粤菜', rating: 4.0, price_range: '¥10-30', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
    { name: '菠萝油', cuisine_type: '粤菜', rating: 4.3, price_range: '¥13-36', is_featured: false, tags: ['特色'], description: '深圳特色美食' },
  ])

  // 苏州美食 (30个)
  addCityFoods('苏州', [
    { name: '松鼠桂鱼', cuisine_type: '苏菜', rating: 4.6, price_range: '¥26-52', is_featured: true, tags: ['必吃', '特色'], description: '苏州特色美食' },
    { name: '响油鳝糊', cuisine_type: '苏菜', rating: 4.9, price_range: '¥29-58', is_featured: true, tags: ['必吃', '特色'], description: '苏州特色美食' },
    { name: '清炒虾仁', cuisine_type: '苏菜', rating: 4.8, price_range: '¥28-76', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '腌笃鲜', cuisine_type: '苏菜', rating: 4.9, price_range: '¥29-58', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '苏式红烧肉', cuisine_type: '苏菜', rating: 4.7, price_range: '¥17-54', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '母油船鸭', cuisine_type: '苏菜', rating: 4.9, price_range: '¥19-68', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '西瓜鸡', cuisine_type: '苏菜', rating: 4.4, price_range: '¥14-48', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '酱方', cuisine_type: '苏菜', rating: 4.5, price_range: '¥15-60', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '碧螺虾仁', cuisine_type: '苏菜', rating: 4.4, price_range: '¥14-38', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '糖粥', cuisine_type: '苏菜', rating: 4.4, price_range: '¥14-58', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '哑巴生煎', cuisine_type: '苏菜', rating: 4.8, price_range: '¥18-66', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '臭豆腐干', cuisine_type: '苏菜', rating: 4.9, price_range: '¥29-78', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '咸肉菜饭', cuisine_type: '苏菜', rating: 4.8, price_range: '¥18-46', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '汤圆', cuisine_type: '苏菜', rating: 4.3, price_range: '¥23-56', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '苏式月饼', cuisine_type: '苏菜', rating: 4.7, price_range: '¥17-54', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '枣泥麻饼', cuisine_type: '苏菜', rating: 4.2, price_range: '¥12-44', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '酥饼', cuisine_type: '苏菜', rating: 4.3, price_range: '¥23-46', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '海棠糕', cuisine_type: '苏菜', rating: 4.8, price_range: '¥28-66', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '青团', cuisine_type: '苏菜', rating: 4.8, price_range: '¥18-56', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '茶糕', cuisine_type: '苏菜', rating: 4.9, price_range: '¥19-58', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '蟹壳黄', cuisine_type: '苏菜', rating: 4.8, price_range: '¥18-56', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '奥灶面', cuisine_type: '苏菜', rating: 4.8, price_range: '¥28-56', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '枫镇大肉面', cuisine_type: '苏菜', rating: 4.4, price_range: '¥14-48', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '藏书羊肉', cuisine_type: '苏菜', rating: 4.9, price_range: '¥29-58', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '叫花鸡', cuisine_type: '苏菜', rating: 4.3, price_range: '¥23-56', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '三虾面', cuisine_type: '苏菜', rating: 4.3, price_range: '¥23-66', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '梅花糕', cuisine_type: '苏菜', rating: 4.8, price_range: '¥18-66', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '海棠糕', cuisine_type: '苏菜', rating: 4.8, price_range: '¥28-66', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '苏州青团', cuisine_type: '苏菜', rating: 4.1, price_range: '¥11-32', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
    { name: '苏州酥饼', cuisine_type: '苏菜', rating: 4.1, price_range: '¥21-42', is_featured: false, tags: ['特色'], description: '苏州特色美食' },
  ])

  // 武汉美食 (30个)
  addCityFoods('武汉', [
    { name: '热干面', cuisine_type: '鄂菜', rating: 4.7, price_range: '¥17-64', is_featured: true, tags: ['必吃', '特色'], description: '武汉特色美食' },
    { name: '三鲜豆皮', cuisine_type: '鄂菜', rating: 4.3, price_range: '¥23-66', is_featured: true, tags: ['必吃', '特色'], description: '武汉特色美食' },
    { name: '鲜鱼糊汤粉', cuisine_type: '鄂菜', rating: 4.5, price_range: '¥15-50', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '油焖小龙虾', cuisine_type: '鄂菜', rating: 4.3, price_range: '¥13-56', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '清蒸武昌鱼', cuisine_type: '鄂菜', rating: 4.0, price_range: '¥10-40', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '排骨藕汤', cuisine_type: '鄂菜', rating: 4.4, price_range: '¥24-68', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '面窝', cuisine_type: '鄂菜', rating: 4.0, price_range: '¥20-50', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '煎饺', cuisine_type: '鄂菜', rating: 4.0, price_range: '¥20-60', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '重油烧麦', cuisine_type: '鄂菜', rating: 4.3, price_range: '¥23-46', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '汤包', cuisine_type: '鄂菜', rating: 4.8, price_range: '¥28-76', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '鸡蛋灌饼', cuisine_type: '鄂菜', rating: 4.7, price_range: '¥27-74', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '油条', cuisine_type: '鄂菜', rating: 4.1, price_range: '¥11-32', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '包子', cuisine_type: '鄂菜', rating: 4.2, price_range: '¥22-64', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '馒头', cuisine_type: '鄂菜', rating: 4.1, price_range: '¥21-52', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '花饭', cuisine_type: '鄂菜', rating: 4.1, price_range: '¥21-42', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '凉面', cuisine_type: '鄂菜', rating: 4.2, price_range: '¥12-34', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '米粉', cuisine_type: '鄂菜', rating: 4.5, price_range: '¥25-50', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '粥', cuisine_type: '鄂菜', rating: 4.7, price_range: '¥27-54', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '牛肉面', cuisine_type: '鄂菜', rating: 4.0, price_range: '¥20-60', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '豆腐脑', cuisine_type: '鄂菜', rating: 4.7, price_range: '¥17-54', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '欢喜坨', cuisine_type: '鄂菜', rating: 4.2, price_range: '¥22-54', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '糯米鸡', cuisine_type: '鄂菜', rating: 4.0, price_range: '¥10-50', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '鸡冠饺', cuisine_type: '鄂菜', rating: 4.7, price_range: '¥27-54', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '糯米包油条', cuisine_type: '鄂菜', rating: 4.2, price_range: '¥12-34', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '汽水包', cuisine_type: '鄂菜', rating: 4.6, price_range: '¥26-52', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '鸭脖', cuisine_type: '鄂菜', rating: 4.5, price_range: '¥25-50', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '周黑鸭', cuisine_type: '鄂菜', rating: 4.1, price_range: '¥11-42', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '精武鸭脖', cuisine_type: '鄂菜', rating: 4.1, price_range: '¥21-62', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '四季美汤包', cuisine_type: '鄂菜', rating: 4.6, price_range: '¥16-42', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
    { name: '蔡林记热干面', cuisine_type: '鄂菜', rating: 4.6, price_range: '¥16-42', is_featured: false, tags: ['特色'], description: '武汉特色美食' },
  ])

  // 厦门美食 (30个)
  addCityFoods('厦门', [
    { name: '沙茶面', cuisine_type: '闽南菜', rating: 4.9, price_range: '¥29-78', is_featured: true, tags: ['必吃', '特色'], description: '厦门特色美食' },
    { name: '海蛎煎', cuisine_type: '闽南菜', rating: 4.7, price_range: '¥17-44', is_featured: true, tags: ['必吃', '特色'], description: '厦门特色美食' },
    { name: '炸五香', cuisine_type: '闽南菜', rating: 4.9, price_range: '¥19-48', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '花生汤', cuisine_type: '闽南菜', rating: 4.8, price_range: '¥18-46', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '土笋冻', cuisine_type: '闽南菜', rating: 4.3, price_range: '¥23-66', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '满煎糕', cuisine_type: '闽南菜', rating: 4.8, price_range: '¥18-46', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '四果汤', cuisine_type: '闽南菜', rating: 4.3, price_range: '¥23-56', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '同安封肉', cuisine_type: '闽南菜', rating: 4.7, price_range: '¥27-54', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '大肠血', cuisine_type: '闽南菜', rating: 4.6, price_range: '¥16-62', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '厦门薄饼', cuisine_type: '闽南菜', rating: 4.3, price_range: '¥23-46', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '烧肉粽', cuisine_type: '闽南菜', rating: 4.4, price_range: '¥24-58', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '姜母鸭', cuisine_type: '闽南菜', rating: 4.1, price_range: '¥21-52', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '油墩子', cuisine_type: '闽南菜', rating: 4.0, price_range: '¥20-50', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '面线糊', cuisine_type: '闽南菜', rating: 4.5, price_range: '¥25-60', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '五香条', cuisine_type: '闽南菜', rating: 4.3, price_range: '¥13-46', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '碗仔粿', cuisine_type: '闽南菜', rating: 4.2, price_range: '¥22-44', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '烧仙草', cuisine_type: '闽南菜', rating: 4.7, price_range: '¥17-44', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '冬瓜茶', cuisine_type: '闽南菜', rating: 4.5, price_range: '¥15-40', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '凤梨酥', cuisine_type: '闽南菜', rating: 4.5, price_range: '¥25-70', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '鱼丸汤', cuisine_type: '闽南菜', rating: 4.8, price_range: '¥28-66', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '芋包', cuisine_type: '闽南菜', rating: 4.3, price_range: '¥13-46', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '虾面', cuisine_type: '闽南菜', rating: 4.4, price_range: '¥14-48', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '鸭肉粥', cuisine_type: '闽南菜', rating: 4.9, price_range: '¥29-58', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '韭菜盒', cuisine_type: '闽南菜', rating: 4.7, price_range: '¥17-64', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '薄饼', cuisine_type: '闽南菜', rating: 4.3, price_range: '¥23-56', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '马蹄酥', cuisine_type: '闽南菜', rating: 4.7, price_range: '¥17-44', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '沙茶酱', cuisine_type: '闽南菜', rating: 4.8, price_range: '¥28-76', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '厦门海鲜', cuisine_type: '闽南菜', rating: 4.6, price_range: '¥26-72', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '鼓浪屿馅饼', cuisine_type: '闽南菜', rating: 4.7, price_range: '¥27-64', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
    { name: '黄则和花生汤', cuisine_type: '闽南菜', rating: 4.8, price_range: '¥18-46', is_featured: false, tags: ['特色'], description: '厦门特色美食' },
  ])

  // 西安美食 (28个)
  addCityFoods('西安', [
    { name: '肉夹馍', cuisine_type: '西北菜', rating: 4.7, price_range: '¥17-54', is_featured: true, tags: ['必吃', '特色'], description: '西安特色美食' },
    { name: '凉皮', cuisine_type: '西北菜', rating: 4.0, price_range: '¥20-50', is_featured: true, tags: ['必吃', '特色'], description: '西安特色美食' },
    { name: 'Biangbiang面', cuisine_type: '西北菜', rating: 4.8, price_range: '¥28-76', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '牛肉泡馍', cuisine_type: '西北菜', rating: 4.9, price_range: '¥19-68', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '葫芦头', cuisine_type: '西北菜', rating: 4.1, price_range: '¥11-52', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '粉蒸肉', cuisine_type: '西北菜', rating: 4.8, price_range: '¥28-56', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '臊子面', cuisine_type: '西北菜', rating: 4.8, price_range: '¥28-56', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '油泼面', cuisine_type: '西北菜', rating: 4.3, price_range: '¥23-56', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '锅盔', cuisine_type: '西北菜', rating: 4.8, price_range: '¥18-46', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '胡辣汤', cuisine_type: '西北菜', rating: 4.3, price_range: '¥23-66', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '甑糕', cuisine_type: '西北菜', rating: 4.8, price_range: '¥18-66', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '灌汤包', cuisine_type: '西北菜', rating: 4.9, price_range: '¥29-68', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '烧饼', cuisine_type: '西北菜', rating: 4.2, price_range: '¥22-54', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '腊汁肉', cuisine_type: '西北菜', rating: 4.4, price_range: '¥14-38', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '水盆羊肉', cuisine_type: '西北菜', rating: 4.0, price_range: '¥20-50', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '黄桂柿子饼', cuisine_type: '西北菜', rating: 4.1, price_range: '¥21-52', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '酸梅汤', cuisine_type: '西北菜', rating: 4.6, price_range: '¥16-62', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '冰峰汽水', cuisine_type: '西北菜', rating: 4.1, price_range: '¥21-42', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '铜锣烧', cuisine_type: '西北菜', rating: 4.9, price_range: '¥29-78', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '肉丸糊辣汤', cuisine_type: '西北菜', rating: 4.7, price_range: '¥17-64', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '小炒泡馍', cuisine_type: '西北菜', rating: 4.9, price_range: '¥29-68', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '南瓜盖被', cuisine_type: '西北菜', rating: 4.0, price_range: '¥10-40', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '腊汁肉夹馍', cuisine_type: '西北菜', rating: 4.1, price_range: '¥21-52', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '金线油塔', cuisine_type: '西北菜', rating: 4.0, price_range: '¥10-30', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '石子馍', cuisine_type: '西北菜', rating: 4.0, price_range: '¥20-60', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '荞面饸饹', cuisine_type: '西北菜', rating: 4.4, price_range: '¥24-58', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '柿子糊塌', cuisine_type: '西北菜', rating: 4.4, price_range: '¥14-38', is_featured: false, tags: ['特色'], description: '西安特色美食' },
    { name: '羊肉泡馍', cuisine_type: '西北菜', rating: 4.5, price_range: '¥25-70', is_featured: false, tags: ['特色'], description: '西安特色美食' },
  ])

  // 张家界美食 (29个)
  addCityFoods('张家界', [
    { name: '土家三下锅', cuisine_type: '湘菜', rating: 4.6, price_range: '¥26-72', is_featured: true, tags: ['必吃', '特色'], description: '张家界特色美食' },
    { name: '岩耳炖鸡', cuisine_type: '湘菜', rating: 4.9, price_range: '¥19-48', is_featured: true, tags: ['必吃', '特色'], description: '张家界特色美食' },
    { name: '土家腊肉', cuisine_type: '湘菜', rating: 4.0, price_range: '¥20-50', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '土家血豆腐', cuisine_type: '湘菜', rating: 4.1, price_range: '¥21-42', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '蒿子粑粑', cuisine_type: '湘菜', rating: 4.0, price_range: '¥10-40', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '合渣', cuisine_type: '湘菜', rating: 4.5, price_range: '¥15-50', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '草帽面', cuisine_type: '湘菜', rating: 4.8, price_range: '¥18-66', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '糖油粑粑', cuisine_type: '湘菜', rating: 4.0, price_range: '¥10-40', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '土家粉蒸肉', cuisine_type: '湘菜', rating: 4.1, price_range: '¥11-52', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '社饭', cuisine_type: '湘菜', rating: 4.2, price_range: '¥12-54', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '糍粑', cuisine_type: '湘菜', rating: 4.2, price_range: '¥22-64', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '腊猪蹄', cuisine_type: '湘菜', rating: 4.4, price_range: '¥24-48', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '土家香肠', cuisine_type: '湘菜', rating: 4.3, price_range: '¥23-66', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '玉米饭', cuisine_type: '湘菜', rating: 4.9, price_range: '¥19-68', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '张家界米粉', cuisine_type: '湘菜', rating: 4.5, price_range: '¥25-60', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '豆腐脑', cuisine_type: '湘菜', rating: 4.7, price_range: '¥17-54', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '油条', cuisine_type: '湘菜', rating: 4.1, price_range: '¥11-32', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '包子', cuisine_type: '湘菜', rating: 4.2, price_range: '¥22-64', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '馒头', cuisine_type: '湘菜', rating: 4.1, price_range: '¥21-52', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '粥', cuisine_type: '湘菜', rating: 4.7, price_range: '¥27-54', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '葛根粉', cuisine_type: '湘菜', rating: 4.2, price_range: '¥22-54', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '猕猴桃', cuisine_type: '湘菜', rating: 4.3, price_range: '¥13-36', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '岩耳', cuisine_type: '湘菜', rating: 4.9, price_range: '¥29-78', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '杜仲茶', cuisine_type: '湘菜', rating: 4.5, price_range: '¥15-40', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '张家界酒', cuisine_type: '湘菜', rating: 4.1, price_range: '¥21-52', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '土家鸡', cuisine_type: '湘菜', rating: 4.8, price_range: '¥18-46', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '土家蒸肉', cuisine_type: '湘菜', rating: 4.0, price_range: '¥10-40', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '土家腌菜', cuisine_type: '湘菜', rating: 4.8, price_range: '¥28-76', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
    { name: '土家腊八', cuisine_type: '湘菜', rating: 4.6, price_range: '¥26-72', is_featured: false, tags: ['特色'], description: '张家界特色美食' },
  ])

  return foods
}