import os
import time
import requests
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager

# --- 配置 ---
BASE_DIR = "images/foods"
FOOD_DATA = {
    # ===== 北京美食 (30+) =====
    "beijing_kaoya": "北京烤鸭",
    "beijing_zhajiangmian": "老北京炸酱面",
    "beijing_shuanyangrou": "涮羊肉",
    "beijing_douzhir": "豆汁儿",
    "beijing_luzhu": "卤煮火烧",
    "beijing_baodu": "爆肚",
    "beijing_menbing": "门钉肉饼",
    "beijing_zhizi": "炙子烤肉",
    "beijing_chaogan": "炒肝",
    "beijing_wandouhuang": "豌豆黄",
    "beijing_zhaguan": "炸灌肠",
    "beijing_majiangbing": "麻酱糖饼",
    "beijing_jiaoquan": "焦圈",
    "beijing_aiwowo": "艾窝窝",
    "beijing_meiguibing": "玫瑰饼",
    "beijing_niushebing": "牛舌饼",
    "beijing_tanghulu": "糖葫芦",
    "beijing_fulingbing": "茯苓饼",
    "beijing_zhengmingzhai": "正明斋糕点",
    "beijing_jingbajian": "京八件",
    "beijing_lvdagun": "驴打滚",
    "beijing_naiyouzhagao": "奶油炸糕",
    "beijing_miancha": "面茶",
    "beijing_xiaodiaolitang": "小吊梨汤",
    "beijing_congshaohaishen": "葱烧海参",
    "beijing_jingjiangrousi": "京酱肉丝",
    "beijing_jiuzhuandachang": "九转大肠",
    "beijing_zaoqianbing": "枣钱饼",
    "beijing_chuitangren": "吹糖人",
    "beijing_liudaju": "柳泉居面点",
    
    # ===== 上海美食 (30+) =====
    "shanghai_xiaolongbao": "小笼包",
    "shanghai_shengjian": "生煎包",
    "shanghai_hongshaorou": "本帮红烧肉",
    "shanghai_youbaoxian": "油爆虾",
    "shanghai_cuiniurou": "脆牛肉",
    "shanghai_baoyu": "糟钵头",
    "shanghai_kaiyangcong": "开洋葱油拌面",
    "shanghai_tangcu": "糖醋小排",
    "shanghai_sanhuang": "三黄鸡",
    "shanghai_cifan": "粢饭糕",
    "shanghai_doufu": "臭豆腐",
    "shanghai_niunan": "咖喱牛肉汤",
    "shanghai_paigu": "排骨年糕",
    "shanghai_baiye": "四喜烤麸",
    "shanghai_xiangchang": "上海香肠",
    "shanghai_hundun": "大馄饨",
    "shanghai_cai": "上海青",
    "shanghai_dousha": "豆沙包",
    "shanghai_lvdou": "绿豆糕",
    "shanghai_tangyuan": "擂沙汤圆",
    "shanghai_xiekehuang": "蟹壳黄",
    "shanghai_nanxiang": "南翔小笼包",
    "shanghai_xianrouyuebing": "鲜肉月饼",
    "shanghai_ligaotang": "梨膏糖",
    "shanghai_wuxiangdou": "五香豆",
    "shanghai_gaogiaosongbing": "高桥松饼",
    "shanghai_tiaotougao": "条头糕",
    "shanghai_you Doufu xianfen": "油豆腐线粉汤",
    "shanghai_shengdabai": "沈大成糕点",
    "shanghai_guojifandian": "国际饭店蝴蝶酥",
    
    # ===== 西安美食 (30+) =====
    "xian_roujiamo": "肉夹馍",
    "xian_liangpi": "凉皮",
    "xian_biangbiang": "Biangbiang面",
    "xian_yangroupaomo": "牛肉泡馍",
    "xian_hulutou": "葫芦头",
    "xian_fenzheng": "粉蒸肉",
    "xian_shaozi": "臊子面",
    "xian_youpo": "油泼面",
    "xian_guokui": "锅盔",
    "xian_hulao": "胡辣汤",
    "xian_jinggao": "甑糕",
    "xian_baozi": "灌汤包",
    "xian_shaobing": "烧饼",
    "xian_lazhi": "腊汁肉",
    "xian_yangrou": "水盆羊肉",
    "xian_huanggui": "黄桂柿子饼",
    "xian_suanmei": "酸梅汤",
    "xian_bingfeng": "冰峰汽水",
    "xian_tongluo": "铜锣烧",
    "xian_rouwan": "肉丸糊辣汤",
    "xian_xiaochaopaomo": "小炒泡馍",
    "xian_nangai": "南瓜盖被",
    "xian_lazhirou": "腊汁肉夹馍",
    "xian_jinxianyouta": "金线油塔",
    "xian_shizimo": "石子馍",
    "xian_qiaomianhele": "荞面饸饹",
    "xian_shizihuta": "柿子糊塌",
    "xian_yangroupaomo2": "羊肉泡馍",
    
    # ===== 成都美食 (30+) =====
    "chengdu_malaxiangguo": "麻辣香锅",
    "chengdu_mapo": "麻婆豆腐",
    "chengdu_huoguo": "四川火锅",
    "chengdu_gongbao": "宫保鸡丁",
    "chengdu_shuizhu": "水煮牛肉",
    "chengdu_huiguorou": "回锅肉",
    "chengdu_fuqifeipian": "夫妻肺片",
    "chengdu_dandan": "担担面",
    "chengdu_chuanchuan": "串串香",
    "chengdu_longchaoshou": "龙抄手",
    "chengdu_zhongshuijiao": "钟水饺",
    "chengdu_lai": "赖汤圆",
    "chengdu_suanlafen": "酸辣粉",
    "chengdu_bingfen": "冰粉",
    "chengdu_tianpin": "三大炮",
    "chengdu_tu": "兔头",
    "chengdu_changwang": "肥肠粉",
    "chengdu_ye": "叶儿粑",
    "chengdu_ai": "艾窝窝",
    "chengdu_zhangcha": "樟茶鸭",
    "chengdu_boboji": "钵钵鸡",
    "chengdu_danhonggao": "蛋烘糕",
    "chengdu_tangyouguozi": "糖油果子",
    "chengdu_tangmian": "甜水面",
    "chengdu_hongyou": "红油水饺",
    "chengdu_maonao": "冒菜",
    "chengdu_lengguo": "冷锅串串",
    "chengdu_shaokao": "成都烧烤",
    "chengdu_tianluo": "三哥田螺",
    "chengdu_jiachangmian": "肖家河家常面",
    
    # ===== 杭州美食 (30+) =====
    "hangzhou_xihucuyu": "西湖醋鱼",
    "hangzhou_pianer": "片儿川",
    "hangzhou_congbao": "葱包桧儿",
    "hangzhou_songsaoyugeng": "宋嫂鱼羹",
    "hangzhou_ganzha": "干炸响铃",
    "hangzhou_henian": "荷叶粉蒸肉",
    "hangzhou_xiaoji": "小鸡酥",
    "hangzhou_dingsheng": "南宋定胜糕",
    "hangzhou_zhixiao": "知味小笼",
    "hangzhou_wushan": "吴山酥油饼",
    "hangzhou_maoer": "杭州猫耳朵",
    "hangzhou_maqiu": "麻球王",
    "hangzhou_longjing": "龙井虾仁",
    "hangzhou_jiao": "叫花鸡",
    "hangzhou_bai": "白切鸡",
    "hangzhou_tang": "糖桂花",
    "hangzhou_lvdou": "绿豆糕",
    "hangzhou_cifan": "粢饭团",
    "hangzhou_you": "油条",
    "hangzhou_chuncai": "西湖莼菜汤",
    "hangzhou_xiabao": "虾爆鳝面",
    "hangzhou_oufen": "西湖藕粉",
    "hangzhou_hehua": "荷花酥",
    "hangzhou_dingsheng2": "定胜糕",
    "hangzhou_cuyu": "醋鱼",
    "hangzhou_dongporou": "东坡肉",
    "hangzhou_xiaolong": "杭州小笼",
    "hangzhou_youtiao": "杭州油条",
    "hangzhou_cifantuan": "杭州粢饭",
    
    # ===== 重庆美食 (30+) =====
    "chongqing_huoguo": "重庆火锅",
    "chongqing_xiaomian": "重庆小面",
    "chongqing_suanlafen": "酸辣粉",
    "chongqing_malaxiang": "麻辣香锅",
    "chongqing_maoxuewang": "毛血旺",
    "chongqing_shuizhu": "水煮鱼",
    "chongqing_laziji": "辣子鸡",
    "chongqing_douhua": "豆花饭",
    "chongqing_baba": "重庆粑粑",
    "chongqing_ciba": "糍粑",
    "chongqing_liushui": "流水席",
    "chongqing_babaofan": "八宝饭",
    "chongqing_suanmian": "酸萝卜面",
    "chongqing_bingfen": "冰粉",
    "chongqing_liangfen": "凉粉",
    "chongqing_liuxiang": "留香鸡",
    "chongqing_chuan": "串串香",
    "chongqing_ban": "板凳面",
    "chongqing_wan": "豌杂面",
    "chongqing_shaomai": "烧麦",
    "chongqing_jizha": "鸡杂",
    "chongqing_kaoyu": "烤鱼",
    "chongqing_qianjiang": "黔江鸡杂",
    "chongqing_fuling": "涪陵榨菜",
    "chongqing_hechuan": "合川桃片",
    "chongqing_jiangjin": "江津米花糖",
    "chongqing_chenmahua": "陈麻花",
    "chongqing_shancheng": "山城小汤圆",
    "chongqing_maoliangfen": "毛凉粉",
    "chongqing_huiguorou": "重庆回锅肉",
    
    # ===== 广州美食 (30+) =====
    "guangzhou_xiajiao": "虾饺",
    "guangzhou_chashaobao": "叉烧包",
    "guangzhou_danta": "蛋挞",
    "guangzhou_malagao": "马拉糕",
    "guangzhou_shaomai": "干蒸烧卖",
    "guangzhou_naicha": "奶黄包",
    "guangzhou_fengzhao": "陈醋凤爪",
    "guangzhou_jinqian": "沙爹金钱肚",
    "guangzhou_hongmi": "红米肠",
    "guangzhou_tingzai": "艇仔粥",
    "guangzhou_changfen": "肠粉",
    "guangzhou_baiqie": "白切鸡",
    "guangzhou_shaoe": "烧鹅",
    "guangzhou_lachang": "腊肠",
    "guangzhou_lurou": "卤肉饭",
    "guangzhou_shuangpinai": "双皮奶",
    "guangzhou_ginger": "姜撞奶",
    "guangzhou_yun": "云吞面",
    "guangzhou_sheng": "生滚粥",
    "guangzhou_liang": "凉茶",
    "guangzhou_jidi": "及第粥",
    "guangzhou_luobu": "萝卜牛杂",
    "guangzhou_jizaibing": "鸡仔饼",
    "guangzhou_laopobing": "老婆饼",
    "guangzhou_yuebing": "广式月饼",
    "guangzhou_matigao": "马蹄糕",
    "guangzhou_lunjiao": "伦教糕",
    "guangzhou_shahe": "沙河粉",
    "guangzhou_baozaifan": "煲仔饭",
    "guangzhou_zhaji": "豉油鸡",
    
    # ===== 苏州美食 (30+) =====
    "suzhou_songshu": "松鼠桂鱼",
    "suzhou_xiangyou": "响油鳝糊",
    "suzhou_qingchao": "清炒虾仁",
    "suzhou_yandu": "腌笃鲜",
    "suzhou_hongshaorou": "苏式红烧肉",
    "suzhou_muyou": "母油船鸭",
    "suzhou_xigua": "西瓜鸡",
    "suzhou_jiangfang": "酱方",
    "suzhou_biluo": "碧螺虾仁",
    "suzhou_tang": "糖粥",
    "suzhou_guotie": "哑巴生煎",
    "suzhou_doufu": "臭豆腐干",
    "suzhou_mifan": "咸肉菜饭",
    "suzhou_yuan": "汤圆",
    "suzhou_bing": "苏式月饼",
    "suzhou_zaoni": "枣泥麻饼",
    "suzhou_su": "酥饼",
    "suzhou_gao": "海棠糕",
    "suzhou_tuan": "青团",
    "suzhou_cha": "茶糕",
    "suzhou_xiekehuang": "蟹壳黄",
    "suzhou_aozao": "奥灶面",
    "suzhou_fengzhen": "枫镇大肉面",
    "suzhou_cangshu": "藏书羊肉",
    "suzhou_jiaohuaji": "叫花鸡",
    "suzhou_sanxia": "三虾面",
    "suzhou_meihuagao": "梅花糕",
    "suzhou_haitang": "海棠糕",
    "suzhou_qingtuan": "苏州青团",
    "suzhou_sushibing": "苏州酥饼",
    
    # ===== 厦门美食 (30+) =====
    "xiamen_shachamian": "沙茶面",
    "xiamen_hailijian": "海蛎煎",
    "xiamen_zhawuxiang": "炸五香",
    "xiamen_tongsuan": "花生汤",
    "xiamen_tusundong": "土笋冻",
    "xiamen_manjian": "满煎糕",
    "xiamen_siguo": "四果汤",
    "xiamen_fengwei": "同安封肉",
    "xiamen_dachang": "大肠血",
    "xiamen_bing": "厦门薄饼",
    "xiamen_shaomai": "烧肉粽",
    "xiamen_jiangmu": "姜母鸭",
    "xiamen_youdun": "油墩子",
    "xiamen_mian": "面线糊",
    "xiamen_wuxiang": "五香条",
    "xiamen_gao": "碗仔粿",
    "xiamen_cao": "烧仙草",
    "xiamen_cha": "冬瓜茶",
    "xiamen_binggan": "凤梨酥",
    "xiamen_yu": "鱼丸汤",
    "xiamen_yubao": "芋包",
    "xiamen_xiamian": "虾面",
    "xiamen_yarouzhou": "鸭肉粥",
    "xiamen_jiucaige": "韭菜盒",
    "xiamen_baobing": "薄饼",
    "xiamen_matisu": "马蹄酥",
    "xiamen_shacha": "沙茶酱",
    "xiamen_haixian": "厦门海鲜",
    "xiamen_gulang": "鼓浪屿馅饼",
    "xiamen_huangzehe": "黄则和花生汤",
    
    # ===== 三亚美食 (30+) =====
    "sanya_wenchang": "文昌鸡",
    "sanya_jiaji": "加积鸭",
    "sanya_helexie": "和乐蟹",
    "sanya_dongshan": "东山羊",
    "sanya_baoluo": "抱罗粉",
    "sanya_qingbuliang": "清补凉",
    "sanya_haimian": "海南粉",
    "sanya_yezi": "椰子饭",
    "sanya_zhubafan": "竹筒饭",
    "sanya_heimei": "黑毛猪",
    "sanya_haidan": "海胆蒸蛋",
    "sanya_longxia": "龙虾",
    "sanya_shanbei": "扇贝",
    "sanya_haizhe": "海蜇",
    "sanya_yuba": "鱼煲",
    "sanya_yang": "羊栏酸鱼汤",
    "sanya_li": "黎家竹筒饭",
    "sanya_mian": "海南腌面",
    "sanya_ji": "鸡屎藤粑仔",
    "sanya_tang": "红糖年糕",
    "sanya_yezidong": "椰子冻",
    "sanya_gangmen": "港门粉",
    "sanya_tengqiao": "藤桥排骨",
    "sanya_lizhi": "荔枝木烤鸭",
    "sanya_haixianhuoguo": "海鲜火锅",
    "sanya_yenai": "椰奶清补凉",
    "sanya_huangliu": "黄流老鸭",
    "sanya_haidaxia": "海南大虾",
    "sanya_haidan": "海南海胆",
    "sanya_yeziji": "椰子鸡",
    
    # ===== 青岛美食 (30+) =====
    "qingdao_lachao": "辣炒蛤蜊",
    "qingdao_baoyu": "鲅鱼水饺",
    "qingdao_liuting": "流亭猪蹄",
    "qingdao_haichang": "海肠捞饭",
    "qingdao_lazha": "青岛脂渣",
    "qingdao_chuozi": "李村戳子肉",
    "qingdao_haicai": "海菜凉粉",
    "qingdao_paigu": "排骨米饭",
    "qingdao_guotie": "青岛锅贴",
    "qingdao_laoshan": "崂山菇炖鸡",
    "qingdao_baoyu2": "鲍鱼",
    "qingdao_haican": "海参",
    "qingdao_xia": "大虾",
    "qingdao_haidai": "海带",
    "qingdao_yu": "黄花鱼",
    "qingdao_mian": "青岛大包",
    "qingdao_you": "油条",
    "qingdao_doufu": "豆腐脑",
    "qingdao_shaobing": "烧饼",
    "qingdao_bing": "煎饼果子",
    "qingdao_haixiandaka": "海鲜大咖",
    "qingdao_kaoyouyu": "烤鱿鱼",
    "qingdao_haixianhun": "海鲜馄饨",
    "qingdao_jiangzhuti": "酱猪蹄",
    "qingdao_congyoubing": "葱油饼",
    "qingdao_gedatang": "海鲜疙瘩汤",
    "qingdao_zhalihuang": "炸蛎黄",
    "qingdao_yuanke": "原壳鲍鱼",
    "qingdao_roumoshen": "肉末海参",
    "qingdao_baozi": "青岛大包",
    
    # ===== 南京美食 (30+) =====
    "nanjing_yaxue": "鸭血粉丝汤",
    "nanjing_guotie": "牛肉锅贴",
    "nanjing_yanshui": "盐水鸭",
    "nanjing_kaoya": "南京烤鸭",
    "nanjing_pidu": "皮肚面",
    "nanjing_tangbao": "鸡鸣汤包",
    "nanjing_hongzao": "红枣糕",
    "nanjing_shao": "秦淮八绝",
    "nanjing_huangqiao": "黄桥烧饼",
    "nanjing_gansi": "开洋干丝",
    "nanjing_niurou": "牛肉汤",
    "nanjing_doufu": "臭豆腐",
    "nanjing_mala": "麻辣小龙虾",
    "nanjing_tang": "糖芋苗",
    "nanjing_chi": "赤豆元宵",
    "nanjing_mei": "梅花糕",
    "nanjing_su": "酥烧饼",
    "nanjing_cai": "菜包",
    "nanjing_rou": "肉包",
    "nanjing_zhou": "美龄粥",
    "nanjing_guihua": "桂花糕",
    "nanjing_ruyi": "如意回卤干",
    "nanjing_shijin": "什锦豆腐涝",
    "nanjing_zhuangyuan": "状元豆",
    "nanjing_wangjidan": "旺鸡蛋",
    "nanjing_huozhuzi": "活珠子",
    "nanjing_honglan": "洪蓝玉带糕",
    "nanjing_dongba": "东坝豆腐干",
    "nanjing_yaxue2": "南京鸭血粉丝",
    "nanjing_yaxue3": "鸭血粉丝",
    
    # ===== 武汉美食 (30+) =====
    "wuhan_regan": "热干面",
    "wuhan_doupi": "三鲜豆皮",
    "wuhan_hutang": "鲜鱼糊汤粉",
    "wuhan_longxia": "油焖小龙虾",
    "wuhan_wuchang": "清蒸武昌鱼",
    "wuhan_outang": "排骨藕汤",
    "wuhan_mianwo": "面窝",
    "wuhan_jianjiao": "煎饺",
    "wuhan_shaomai": "重油烧麦",
    "wuhan_tangbao": "汤包",
    "wuhan_jidan": "鸡蛋灌饼",
    "wuhan_you": "油条",
    "wuhan_baozi": "包子",
    "wuhan_mantou": "馒头",
    "wuhan_huafan": "花饭",
    "wuhan_liang": "凉面",
    "wuhan_mifen": "米粉",
    "wuhan_zhou": "粥",
    "wuhan_niurou": "牛肉面",
    "wuhan_doufu": "豆腐脑",
    "wuhan_huanxitu": "欢喜坨",
    "wuhan_nuomiji": "糯米鸡",
    "wuhan_jiguanjiao": "鸡冠饺",
    "wuhan_nuomiyoutiao": "糯米包油条",
    "wuhan_qishuibao": "汽水包",
    "wuhan_yabo": "鸭脖",
    "wuhan_zhouheiya": "周黑鸭",
    "wuhan_jingwuyabo": "精武鸭脖",
    "wuhan_sijimei": "四季美汤包",
    "wuhan_cailinji": "蔡林记热干面",
    
    # ===== 长沙美食 (30+) =====
    "changsha_choudoufu": "长沙臭豆腐",
    "changsha_tangyou": "糖油粑粑",
    "changsha_kouweixia": "口味虾",
    "changsha_jiangban": "湖南酱板鸭",
    "changsha_mifen": "长沙米粉",
    "changsha_deyuan": "德园包子",
    "changsha_longzhi": "龙脂猪血",
    "changsha_suoluo": "嗍螺",
    "changsha_hongshao": "红烧猪脚",
    "changsha_kouweixie": "口味蟹",
    "changsha_labi": "辣椒炒肉",
    "changsha_dongcai": "剁椒鱼头",
    "changsha_zheng": "蒸菜",
    "changsha_liangfen": "刮凉粉",
    "changsha_youzha": "油炸串串",
    "changsha_cha": "茶颜悦色",
    "changsha_xiaolong": "小龙虾",
    "changsha_tian": "甜酒冲蛋",
    "changsha_mao": "毛氏红烧肉",
    "changsha_bing": "冰粉",
    "changsha_zimei": "姊妹团子",
    "changsha_helan": "荷兰粉",
    "changsha_malaziji": "麻辣子鸡",
    "changsha_sanceng": "三层套鸡",
    "changsha_gaodian": "长沙糕点",
    "changsha_liuyang": "浏阳蒸菜",
    "changsha_hefan": "长沙盒饭",
    "changsha_xiangxia": "湘西外婆菜",
    
    # ===== 深圳美食 (30+) =====
    "shenzhen_guangming": "光明乳鸽",
    "shenzhen_gongming": "公明烧鹅",
    "shenzhen_shen": "深井烧鹅",
    "shenzhen_shae": "沙井蚝",
    "shenzhen_nantou": "南头荔枝",
    "shenzhen_futian": "福田云吞",
    "shenzhen_luohu": "罗湖肠粉",
    "shenzhen_longgang": "龙岗鸡",
    "shenzhen_baoan": "宝安腊鸭",
    "shenzhen_yantian": "盐田海鲜",
    "shenzhen_dameisha": "大梅沙海鲜",
    "shenzhen_xiaomeisha": "小梅沙烧烤",
    "shenzhen_chun": "春满园早茶",
    "shenzhen_dian": "点都德",
    "shenzhen_taotaoju": "陶陶居",
    "shenzhen_lianxiang": "莲香楼",
    "shenzhen_guangzhou": "广州酒家",
    "shenzhen_panxi": "泮溪酒家",
    "shenzhen_beiyuan": "北园酒家",
    "shenzhen_dongjiang": "东江盐焗鸡",
    "shenzhen_zhuduji": "猪肚鸡",
    "shenzhen_yeziji": "椰子鸡",
    "shenzhen_chaoshan": "潮汕牛肉火锅",
    "shenzhen_guangshi": "广式早茶",
    "shenzhen_changfen": "肠粉",
    "shenzhen_chashao": "叉烧",
    "shenzhen_shaoe": "烧鹅饭",
    "shenzhen_naicha": "港式奶茶",
    "shenzhen_jidan": "鸡蛋仔",
    "shenzhen_boluoyou": "菠萝油",
    
    # ===== 桂林美食 (30+) =====
    "guilin_mifen": "桂林米粉",
    "guilin_lipu": "荔浦扣肉",
    "guilin_pijiu": "阳朔啤酒鱼",
    "guilin_quanzhou": "全州醋血鸭",
    "guilin_pingyue": "平乐十八酿",
    "guilin_marou": "桂林马肉米粉",
    "guilin_hehua": "全州禾花鱼",
    "guilin_yangshuo": "阳朔田螺酿",
    "guilin_gongcheng": "恭城油茶",
    "guilin_longsheng": "龙脊竹筒饭",
    "guilin_xingan": "兴安白果",
    "guilin_yangshuo2": "阳朔糍粑",
    "guilin_guanyan": "灌阳红薯粉",
    "guilin_ziyuan": "资源竹笋",
    "guilin_yongfu": "永福罗汉果",
    "guilin_pingle": "平乐沙田柚",
    "guilin_gongcheng2": "恭城月柿",
    "guilin_li": "荔浦芋",
    "guilin_sanhuajiu": "桂林三花酒",
    "guilin_tianluo": "桂林田螺",
    "guilin_matigao": "马蹄糕",
    "guilin_guihuagao": "桂花糕",
    "guilin_nigusu": "尼姑素面",
    "guilin_songgao": "桂林松糕",
    "guilin_shuiciba": "桂林水糍粑",
    "guilin_furu": "桂林腐乳",
    "guilin_lajiao": "桂林辣椒酱",
    "guilin_pijiu2": "阳朔啤酒",
    "guilin_luohanguo": "罗汉果",
    
    # ===== 张家界美食 (30+) =====
    "zhangjiajie_sanxiaguo": "土家三下锅",
    "zhangjiajie_yaner": "岩耳炖鸡",
    "zhangjiajie_larou": "土家腊肉",
    "zhangjiajie_xuedoufu": "土家血豆腐",
    "zhangjiajie_haozi": "蒿子粑粑",
    "zhangjiajie_hezha": "合渣",
    "zhangjiajie_caomao": "草帽面",
    "zhangjiajie_tangyou": "糖油粑粑",
    "zhangjiajie_tujia": "土家粉蒸肉",
    "zhangjiajie_shefan": "社饭",
    "zhangjiajie_ciba": "糍粑",
    "zhangjiajie_la": "腊猪蹄",
    "zhangjiajie_xiangchang": "土家香肠",
    "zhangjiajie_yumi": "玉米饭",
    "zhangjiajie_mifen": "张家界米粉",
    "zhangjiajie_doufu": "豆腐脑",
    "zhangjiajie_you": "油条",
    "zhangjiajie_baozi": "包子",
    "zhangjiajie_mantou": "馒头",
    "zhangjiajie_zhou": "粥",
    "zhangjiajie_gegen": "葛根粉",
    "zhangjiajie_mihoutao": "猕猴桃",
    "zhangjiajie_yaner2": "岩耳",
    "zhangjiajie_duzhong": "杜仲茶",
    "zhangjiajie_zhangjiajiejiu": "张家界酒",
    "zhangjiajie_tuji": "土家鸡",
    "zhangjiajie_tujiazhengrou": "土家蒸肉",
    "zhangjiajie_tujiayancai": "土家腌菜",
    "zhangjiajie_tujialaba": "土家腊八",
    
    # ===== 黄山美食 (30+) =====
    "huangshan_chouguiyu": "徽州臭鳜鱼",
    "huangshan_maodoufu": "徽州毛豆腐",
    "huangshan_shaobing": "黄山烧饼",
    "huangshan_daoban": "徽州刀板香",
    "huangshan_wenzheng": "问政山笋",
    "huangshan_shuangshi": "黄山双石",
    "huangshan_wucheng": "五城茶干",
    "huangshan_dunge": "黄山炖鸽",
    "huangshan_yuanzi": "徽州圆子",
    "huangshan_juecai": "黄山蕨菜",
    "huangshan_hongshao": "红烧臭鳜鱼",
    "huangshan_wenzheng2": "问政山笋煲",
    "huangshan_hushi": "胡适一品锅",
    "huangshan_huotui": "火腿炖甲鱼",
    "huangshan_shadi": "沙地马蹄鳖",
    "huangshan_xuetian": "雪天牛尾狸",
    "huangshan_shier": "石耳炖石鸡",
    "huangshan_ta": "挞粿",
    "huangshan_mao": "毛豆腐",
    "huangshan_you": "油煎毛豆腐",
    "huangshan_guozong": "徽州裹粽",
    "huangshan_zhuangyuan": "徽州状元饭",
    "huangshan_humaodoufu": "虎皮毛豆腐",
    "huangshan_shiji": "徽州石鸡",
    "huangshan_taozhi": "徽州桃脂烧肉",
    "huangshan_dunge2": "黄山炖鸽",
    "huangshan_zhengji": "徽州蒸鸡",
    "huangshan_yixian": "黟县腊八豆腐",
    "huangshan_chou": "徽州臭豆腐",
    "huangshan_mihoutao": "黄山猕猴桃",
    
    # ===== 九寨沟美食 (30+) =====
    "jiuzhaigou_zhaxibing": "九寨柿饼",
    "jiuzhaigou_suancai": "酸菜面块",
    "jiuzhaigou_yangyu": "洋芋糍粑",
    "jiuzhaigou_suyou": "酥油茶",
    "jiuzhaigou_xuechang": "藏族血肠",
    "jiuzhaigou_maoniu": "牦牛肉干",
    "jiuzhaigou_naizha": "奶渣包子",
    "jiuzhaigou_niuzai": "藏民奶制品",
    "jiuzhaigou_qiaomai": "荞麦面食",
    "jiuzhaigou_wanza": "豌杂面",
    "jiuzhaigou_zanba": "糌粑",
    "jiuzhaigou_maoniurou": "牦牛肉",
    "jiuzhaigou_qiaomai2": "荞麦饼",
    "jiuzhaigou_qingke": "青稞酒",
    "jiuzhaigou_suannai": "酸奶",
    "jiuzhaigou_nai": "奶茶",
    "jiuzhaigou_yang": "羊肉汤",
    "jiuzhaigou_niu": "牛肉汤",
    "jiuzhaigou_mian": "面条",
    "jiuzhaigou_fan": "米饭",
    "jiuzhaigou_shouzhua": "手抓肉",
    "jiuzhaigou_kaoquanyang": "烤全羊",
    "jiuzhaigou_zanghuoguo": "藏式火锅",
    "jiuzhaigou_rencanguo": "人参果饭",
    "jiuzhaigou_chongcao": "虫草鸭",
    "jiuzhaigou_huanggua": "九寨黄瓜",
    "jiuzhaigou_yangroupaomo": "羊肉泡馍",
    "jiuzhaigou_niurougan": "风干牛肉",
    "jiuzhaigou_naijiao": "奶皮",
    "jiuzhaigou_youzha": "油炸酸奶",
    
    # ===== 大理美食 (30+) =====
    "dali_rushan": "烤乳扇",
    "dali_shengpi": "大理生皮",
    "dali_suanla": "大理酸辣鱼",
    "dali_xizhou": "喜洲粑粑",
    "dali_liangji": "凉鸡米线",
    "dali_shaguo": "砂锅鱼",
    "dali_weishan": "巍山耙肉饵丝",
    "dali_diaomei": "雕梅扣肉",
    "dali_huangmen": "永平黄焖鸡",
    "dali_diaomei2": "雕梅酒",
    "dali_bajian": "白族土八碗",
    "dali_erhai": "大理洱海砂锅鱼",
    "dali_jianchuan": "剑川八大碗",
    "dali_nuodeng": "云龙诺邓火腿",
    "dali_nanjian": "南涧锅巴油粉",
    "dali_yangbi": "漾濞卷粉",
    "dali_binxuan": "宾川韭菜腌菜",
    "dali_kaoer": "烤饵块",
    "dali_dali": "大理凉粉",
    "dali_pa": "耙肉饵丝",
    "dali_guoguo": "大理锅锅菜",
    "dali_baixizhu": "白族三道茶",
    "dali_meizi": "大理梅子",
    "dali_shuangrufan": "双乳扇",
    "dali_heguiyu": "大理黑桂鱼",
    "dali_cangshan": "苍山雪鱼",
    "dali_xuecha": "大理雪茶",
    "dali_xiguajiao": "西瓜酱",
    "dali_yuzhou": "大理鱼粥",
    "dali_yangnai": "羊奶乳扇",
    
    # ===== 丽江美食 (30+) =====
    "lijiang_larou": "腊排骨火锅",
    "lijiang_shuixing": "水性杨花",
    "lijiang_baba": "丽江粑粑",
    "lijiang_naxi": "纳西烤肉",
    "lijiang_jidou": "鸡豆凉粉",
    "lijiang_baojiang": "包浆豆腐",
    "lijiang_hei": "黑山羊火锅",
    "lijiang_songrong": "松茸",
    "lijiang_naxi2": "纳西烤鱼",
    "lijiang_yang": "洋芋鸡",
    "lijiang_qi": "汽锅鸡",
    "lijiang_guo": "过桥米线",
    "lijiang_suan": "酸汤鱼",
    "lijiang_liang": "凉粉",
    "lijiang_mifen": "米线",
    "lijiang_er": "饵丝",
    "lijiang_xiaobaicai": "小白菜",
    "lijiang_qingcai": "青菜",
    "lijiang_tudou": "土豆",
    "lijiang_hongshu": "红薯",
    "lijiang_miguanchang": "米灌肠",
    "lijiang_suyoucha": "酥油茶",
    "lijiang_xuecha": "雪茶",
    "lijiang_luoxuanzao": "螺旋藻",
    "lijiang_dongba": "东巴烤鱼",
    "lijiang_sanwenyu": "三文鱼",
    "lijiang_yeshengjun": "野生菌",
    "lijiang_xianhuabing": "鲜花饼",
    "lijiang_lijiangyan": "丽江腌菜",
    "lijiang_lijiangjiu": "丽江酒",
}

def init_driver():
    options = Options()
    #options.add_argument('--headless') # 建议先关掉 headless 看看能不能搜到，稳了再开
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument('user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')
    service = Service(ChromeDriverManager().install())
    return webdriver.Chrome(service=service, options=options)

def start_scrape():
    if not os.path.exists(BASE_DIR):
        os.makedirs(BASE_DIR, exist_ok=True)

    driver = init_driver()
    print("🚀 浏览器已就绪，开始抓取美食图...")
    print(f"📋 本次共需下载 {len(FOOD_DATA)} 个美食图片\n")

    success_count = 0
    fail_count = 0
    skip_count = 0

    for py_name, cn_name in FOOD_DATA.items():
        filename = f"{py_name}.jpg"
        save_path = os.path.join(BASE_DIR, filename)

        if os.path.exists(save_path):
            print(f"⏭️  {cn_name} 已存在，跳过")
            skip_count += 1
            continue

        print(f"🔍 正在找: {cn_name}...")
        try:
            # 访问下厨房搜索页
            driver.get(f"https://www.xiachufang.com/search/?keyword={cn_name}&cat=1001")
            time.sleep(2)

            # 定位搜索结果的第一张图
            # 下厨房的结构比较清晰，第一个菜谱通常在 .normal-recipe-list li
            first_img = driver.find_element(By.CSS_SELECTOR, ".normal-recipe-list li img")
            img_url = first_img.get_attribute("src")

            # 转换成高清大图（下厨房的缩略图 URL 替换后缀即可）
            # 示例：.../cover/xxx_280.jpg -> .../cover/xxx_660.jpg
            if "_280" in img_url:
                img_url = img_url.replace("_280", "_660")
            elif "?" in img_url:
                img_url = img_url.split("?")[0]

            # 下载图片
            r = requests.get(img_url, timeout=10)
            if r.status_code == 200:
                with open(save_path, 'wb') as f:
                    f.write(r.content)
                print(f"   ✅ {filename} 保存完成")
                success_count += 1
            
            time.sleep(1) # 歇口气

        except Exception as e:
            print(f"   ❌ {cn_name} 抓取失败: {str(e)}")
            fail_count += 1

    driver.quit()
    print("\n" + "="*50)
    print("✨ 任务全部结束！")
    print(f"✅ 成功: {success_count}")
    print(f"⏭️  跳过: {skip_count}")
    print(f"❌ 失败: {fail_count}")
    print(f"📊 总计: {len(FOOD_DATA)}")
    print("="*50)

if __name__ == "__main__":
    start_scrape()
